project:
  type: book
  output-dir: docs

book:
  title: "Quantitative Methods 2"
  author: "Ollie Ballinger"
  date: "10/10/2024"
  google-analytics: UA-154866877-2
  chapters:
    - index.qmd
    - ./notebooks/W01. Python Recap.ipynb
    - ./notebooks/W02. Pandas.ipynb
    - ./notebooks/W03. Spatial Data.ipynb
    - ./notebooks/W04. Natural Language Processing.ipynb
    - ./notebooks/W05. Distributions and Basic Statistics.ipynb
    - ./notebooks/RW. Merging and Joining.ipynb
    - ./notebooks/W06. Hypothesis Testing.ipynb
    - ./notebooks/W07. Linear Regression.ipynb
    - ./notebooks/W08. Diff-in-Diff.ipynb
    - ./notebooks/W09. Regression Discontinuity.ipynb
    # - ./notebooks/W10. Machine Learning.ipynb

  repo-url: https://github.com/oballinger/QM2/
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  sidebar:
    logo: logo2.png
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



