<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Quantitative Methods 2 - Distributions and Basic Statistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../Week 8.html" rel="next">
<link href="../Week 6.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script type="text/javascript">

(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
ga('create', 'UA-154866877-2', 'auto');

ga('send', {
  hitType: 'pageview',
  'anonymizeIp': true,
});
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">Distributions and Basic Statistics</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="../logo.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Quantitative Methods 2</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/oballinger/QM2/" title="Source Code" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
    <a href="" title="Download" id="sidebar-tool-dropdown-0" class="sidebar-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-download"></i></a>
    <ul class="dropdown-menu" aria-labelledby="sidebar-tool-dropdown-0">
        <li>
          <a class="dropdown-item sidebar-tools-main-item" href="../Quantitative-Methods-2.pdf">
            <i class="bi bi-bi-file-pdf pe-1"></i>
          Download PDF
          </a>
        </li>
        <li>
          <a class="dropdown-item sidebar-tools-main-item" href="../Quantitative-Methods-2.epub">
            <i class="bi bi-bi-journal pe-1"></i>
          Download ePub
          </a>
        </li>
    </ul>
    <a href="" title="Share" id="sidebar-tool-dropdown-1" class="sidebar-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-share"></i></a>
    <ul class="dropdown-menu" aria-labelledby="sidebar-tool-dropdown-1">
        <li>
          <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
            <i class="bi bi-bi-twitter pe-1"></i>
          Twitter
          </a>
        </li>
        <li>
          <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
            <i class="bi bi-bi-facebook pe-1"></i>
          Facebook
          </a>
        </li>
    </ul>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">Welcome</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/W01. Python Recap.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Python Recap</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/W02. Pandas.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Intro to Pandas</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/W03. Spatial Data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Spatiotemporal Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/W04. Natural Language Processing.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Natural Language Processing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/W05. Merging and Joining.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Merging and Joining</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Week 6.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Group Presentations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/W07. Distributions and Basic Statistics.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Distributions and Basic Statistics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Week 8.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/W09. Linear Regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Linear Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/W10. Advanced Visualization.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Advanced Visualization</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#workshop-7-open-in-colab" id="toc-workshop-7-open-in-colab" class="nav-link active" data-scroll-target="#workshop-7-open-in-colab"><em>Workshop 7</em> <img src="https://github.com/oballinger/QM2/blob/main/colab-badge.png?raw=1" class="img-fluid" alt="Open In Colab"></a>
  <ul class="collapse">
  <li><a href="#aims" id="toc-aims" class="nav-link" data-scroll-target="#aims">Aims:</a></li>
  </ul></li>
  <li><a href="#getting-started" id="toc-getting-started" class="nav-link" data-scroll-target="#getting-started">Getting Started</a>
  <ul class="collapse">
  <li><a href="#first-things-first-bias" id="toc-first-things-first-bias" class="nav-link" data-scroll-target="#first-things-first-bias">First Things First: Bias</a></li>
  </ul></li>
  <li><a href="#summary-statistics" id="toc-summary-statistics" class="nav-link" data-scroll-target="#summary-statistics">Summary Statistics</a>
  <ul class="collapse">
  <li><a href="#exercise" id="toc-exercise" class="nav-link" data-scroll-target="#exercise">Exercise</a></li>
  </ul></li>
  <li><a href="#distributions" id="toc-distributions" class="nav-link" data-scroll-target="#distributions">Distributions</a>
  <ul class="collapse">
  <li><a href="#exercise-1" id="toc-exercise-1" class="nav-link" data-scroll-target="#exercise-1">Exercise</a></li>
  <li><a href="#functions" id="toc-functions" class="nav-link" data-scroll-target="#functions">Functions</a>
  <ul class="collapse">
  <li><a href="#exercise-2" id="toc-exercise-2" class="nav-link" data-scroll-target="#exercise-2">Exercise</a></li>
  </ul></li>
  <li><a href="#the-central-limit-theorem" id="toc-the-central-limit-theorem" class="nav-link" data-scroll-target="#the-central-limit-theorem">The Central Limit Theorem</a>
  <ul class="collapse">
  <li><a href="#sampling" id="toc-sampling" class="nav-link" data-scroll-target="#sampling">Sampling</a></li>
  <li><a href="#exercise-3" id="toc-exercise-3" class="nav-link" data-scroll-target="#exercise-3">Exercise</a></li>
  <li><a href="#exercise-4" id="toc-exercise-4" class="nav-link" data-scroll-target="#exercise-4">Exercise</a></li>
  <li><a href="#exercise-5" id="toc-exercise-5" class="nav-link" data-scroll-target="#exercise-5">Exercise</a></li>
  <li><a href="#extension" id="toc-extension" class="nav-link" data-scroll-target="#extension">Extension</a></li>
  </ul></li>
  <li><a href="#confidence-intervals" id="toc-confidence-intervals" class="nav-link" data-scroll-target="#confidence-intervals">Confidence Intervals</a>
  <ul class="collapse">
  <li><a href="#sample-standard-deviation" id="toc-sample-standard-deviation" class="nav-link" data-scroll-target="#sample-standard-deviation">Sample Standard Deviation</a></li>
  <li><a href="#standard-error" id="toc-standard-error" class="nav-link" data-scroll-target="#standard-error">Standard Error</a></li>
  </ul></li>
  <li><a href="#hypothesis-testing" id="toc-hypothesis-testing" class="nav-link" data-scroll-target="#hypothesis-testing">Hypothesis Testing</a>
  <ul class="collapse">
  <li><a href="#state-the-hypotheses" id="toc-state-the-hypotheses" class="nav-link" data-scroll-target="#state-the-hypotheses">1. State the hypotheses</a></li>
  <li><a href="#select-an-alpha-level" id="toc-select-an-alpha-level" class="nav-link" data-scroll-target="#select-an-alpha-level">2. Select an <span class="math inline">\(\alpha\)</span> level</a></li>
  <li><a href="#calculate-the-test-statistic-the-students-t-test" id="toc-calculate-the-test-statistic-the-students-t-test" class="nav-link" data-scroll-target="#calculate-the-test-statistic-the-students-t-test">3. Calculate the Test Statistic (The Student’s T-Test)</a></li>
  <li><a href="#make-a-decision" id="toc-make-a-decision" class="nav-link" data-scroll-target="#make-a-decision">4. Make a Decision</a></li>
  <li><a href="#exercise-6" id="toc-exercise-6" class="nav-link" data-scroll-target="#exercise-6">Exercise</a></li>
  </ul></li>
  <li><a href="#extension-1" id="toc-extension-1" class="nav-link" data-scroll-target="#extension-1">Extension</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.dev/oballinger/QM2/blob/main/notebooks/W07. Distributions and Basic Statistics.ipynb" class="toc-action">Edit this page</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">Distributions and Basic Statistics</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="workshop-7-open-in-colab" class="level2">
<h2 class="anchored" data-anchor-id="workshop-7-open-in-colab"><em>Workshop 7</em> <a href="https://colab.research.google.com/github/oballinger/QM2/blob/main/notebooks/W07.%20Distributions%20and%20Basic%20Statistics.ipynb"><img src="https://github.com/oballinger/QM2/blob/main/colab-badge.png?raw=1" class="img-fluid" alt="Open In Colab"></a></h2>
<p>For the rest of this course, we’ll be working with data from the U.S. Census <a href="https://www.census.gov/programs-surveys/cps.html">Current Population Survey (CPS)</a>.</p>
<section id="aims" class="level3">
<h3 class="anchored" data-anchor-id="aims">Aims:</h3>
<ul>
<li><p>Choosing appropriate summary statistics for varying distributions</p></li>
<li><p>Understanding:</p>
<ul>
<li>The nature of our dataset, including potential bias</li>
<li>How to generate summary statistics for our dataset</li>
<li>The distribution of different variables</li>
<li>The intuition behind the Central Limit Theorem</li>
</ul></li>
</ul>
</section>
</section>
<section id="getting-started" class="level2">
<h2 class="anchored" data-anchor-id="getting-started">Getting Started</h2>
<section id="first-things-first-bias" class="level3">
<h3 class="anchored" data-anchor-id="first-things-first-bias">First Things First: Bias</h3>
<p>Once we’ve acquired a dataset, the first step is <em>always</em> to develop an understanding of where the data has come from. For this dataset, use the following <a href="https://www.census.gov/programs-surveys/cps/technical-documentation/methodology.html">documentation page</a> to answer the questions below:</p>
<ol type="1">
<li>What is the population of interest?</li>
<li>What was the sampling strategy?</li>
<li>What are potential sources of selection bias?</li>
</ol>
<p>I’ll start by importing the libraries I need: matplotlib (for graphs), pandas (for data), numpy (for maths) and random (for generating random numbers):</p>
<div class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#This tells python to draw the graphs "inline" - in the notebook</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>matplotlib inline  </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> norm</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statistics</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pylab</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># make the plots (graphs) a little wider by default</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>pylab.rcParams[<span class="st">'figure.figsize'</span>] <span class="op">=</span> (<span class="fl">10.</span>, <span class="fl">8.</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>sns.<span class="bu">set</span>(font_scale<span class="op">=</span><span class="fl">1.5</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>sns.set_style(<span class="st">"white"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>/Users/ollieballinger/.pyenv/versions/3.9.5/lib/python3.9/site-packages/pandas/compat/__init__.py:97: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)</code></pre>
</div>
</div>
<div class="cell" data-outputid="d585f549-6d26-4927-8a95-881a66072bdf" data-execution_count="2">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>mkdir data</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>mkdir data<span class="op">/</span>wk7</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>curl https:<span class="op">//</span>storage.googleapis.com<span class="op">/</span>qm2<span class="op">/</span>wk7<span class="op">/</span>cps.csv <span class="op">-</span>o data<span class="op">/</span>wk7<span class="op">/</span>cps.csv</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>mkdir: data: File exists
mkdir: data/wk7: File exists
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 22.4M  100 22.4M    0     0  12.3M      0  0:00:01  0:00:01 --:--:-- 12.4M</code></pre>
</div>
</div>
<p>Now that I’ve imported the libraries I’m going to be using, I’m ready to import the data:</p>
<div class="cell" data-outputid="eaa86222-5f24-416a-c119-45cf3782f65a" data-execution_count="3">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>df<span class="op">=</span>pd.read_csv(<span class="st">'./data/wk7/cps.csv'</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="3">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>year</th>
      <th>state</th>
      <th>age</th>
      <th>sex</th>
      <th>race</th>
      <th>sch</th>
      <th>ind</th>
      <th>union</th>
      <th>incwage</th>
      <th>realhrwage</th>
      <th>occupation</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1990</td>
      <td>36</td>
      <td>58</td>
      <td>1</td>
      <td>3</td>
      <td>12.0</td>
      <td>871</td>
      <td>0.0</td>
      <td>14200.0</td>
      <td>12.269874</td>
      <td>Office and Admin Support</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2009</td>
      <td>5</td>
      <td>28</td>
      <td>1</td>
      <td>1</td>
      <td>12.0</td>
      <td>8660</td>
      <td>1.0</td>
      <td>17680.0</td>
      <td>8.635149</td>
      <td>Office and Admin Support</td>
    </tr>
    <tr>
      <th>2</th>
      <td>1990</td>
      <td>36</td>
      <td>37</td>
      <td>1</td>
      <td>1</td>
      <td>14.0</td>
      <td>380</td>
      <td>1.0</td>
      <td>28000.0</td>
      <td>21.169851</td>
      <td>.</td>
    </tr>
    <tr>
      <th>3</th>
      <td>1990</td>
      <td>6</td>
      <td>34</td>
      <td>1</td>
      <td>1</td>
      <td>18.0</td>
      <td>740</td>
      <td>1.0</td>
      <td>27500.0</td>
      <td>20.447746</td>
      <td>Computer and Math Technicians</td>
    </tr>
    <tr>
      <th>4</th>
      <td>1981</td>
      <td>51</td>
      <td>38</td>
      <td>1</td>
      <td>4</td>
      <td>13.0</td>
      <td>798</td>
      <td>NaN</td>
      <td>17000.0</td>
      <td>18.892282</td>
      <td>Managers</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>Our dataframe has 10 columns:</p>
<ol type="1">
<li><em>year</em>: Survey year</li>
<li><em>age</em>: the person’s age</li>
<li><em>sex</em>: the person’s sex
<ul>
<li>1=male</li>
<li>2=female</li>
</ul></li>
<li><em>race</em>: the person’s race
<ul>
<li>White non hispanic=1</li>
<li>Black non hispanic=2</li>
<li>Hispanic=3</li>
<li>Other non hispanic=4)</li>
</ul></li>
<li><em>sch</em>: Educational attainment
<ul>
<li>None = 0,</li>
<li>Grades 1-12 = 1-12</li>
<li>Some University = 13,</li>
<li>Associate’s degree = 14,</li>
<li>BA = 16</li>
<li>Advanced Degree = 18</li>
</ul></li>
<li><em>union</em>: Union membership
<ul>
<li>N/A = 0,</li>
<li>No union coverage = 1,</li>
<li>Member of labor union=2,</li>
<li>Covered by union but not a member=3</li>
</ul></li>
<li><em>incwage</em>: Wage and salary income</li>
<li><em>realhrwage</em>: Real Hourly Wage</li>
<li><em>occupation</em>: Occupation</li>
<li><em>ind</em>: <a href="https://www.census.gov/naics/?58967?yearbck=2002">industry code</a></li>
</ol>
</section>
</section>
<section id="summary-statistics" class="level2">
<h2 class="anchored" data-anchor-id="summary-statistics">Summary Statistics</h2>
<p>After thinking about the origins of our dataset and loading it into python, the next step is to generate summary statistics. This is vital for us to better understand our data. Pandas has a useful function, <code>describe</code>, which will generate summary statistics for all numerical variables in our entire dataframe:</p>
<div class="cell" data-outputid="dbaccbc3-e7fc-462f-eda6-5c78029bb630" data-execution_count="4">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>df.describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>year</th>
      <th>state</th>
      <th>age</th>
      <th>sex</th>
      <th>race</th>
      <th>sch</th>
      <th>ind</th>
      <th>union</th>
      <th>incwage</th>
      <th>realhrwage</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>count</th>
      <td>344287.000000</td>
      <td>344287.000000</td>
      <td>344287.000000</td>
      <td>344287.000000</td>
      <td>344287.000000</td>
      <td>344287.000000</td>
      <td>344287.000000</td>
      <td>301908.000000</td>
      <td>3.442870e+05</td>
      <td>344287.000000</td>
    </tr>
    <tr>
      <th>mean</th>
      <td>2002.599122</td>
      <td>28.121004</td>
      <td>41.734364</td>
      <td>1.489057</td>
      <td>1.570077</td>
      <td>13.498057</td>
      <td>4235.846009</td>
      <td>0.221505</td>
      <td>3.976170e+04</td>
      <td>22.886629</td>
    </tr>
    <tr>
      <th>std</th>
      <td>10.831555</td>
      <td>15.818556</td>
      <td>10.415874</td>
      <td>0.499881</td>
      <td>0.952252</td>
      <td>2.799038</td>
      <td>3468.163157</td>
      <td>0.499690</td>
      <td>4.529758e+04</td>
      <td>506.489695</td>
    </tr>
    <tr>
      <th>min</th>
      <td>1981.000000</td>
      <td>1.000000</td>
      <td>25.000000</td>
      <td>1.000000</td>
      <td>1.000000</td>
      <td>0.000000</td>
      <td>10.000000</td>
      <td>0.000000</td>
      <td>1.500000e+01</td>
      <td>2.000000</td>
    </tr>
    <tr>
      <th>25%</th>
      <td>1990.000000</td>
      <td>13.000000</td>
      <td>33.000000</td>
      <td>1.000000</td>
      <td>1.000000</td>
      <td>12.000000</td>
      <td>760.000000</td>
      <td>0.000000</td>
      <td>1.670000e+04</td>
      <td>11.723004</td>
    </tr>
    <tr>
      <th>50%</th>
      <td>2007.000000</td>
      <td>28.000000</td>
      <td>41.000000</td>
      <td>1.000000</td>
      <td>1.000000</td>
      <td>13.000000</td>
      <td>4270.000000</td>
      <td>0.000000</td>
      <td>3.000000e+04</td>
      <td>17.698591</td>
    </tr>
    <tr>
      <th>75%</th>
      <td>2011.000000</td>
      <td>41.000000</td>
      <td>50.000000</td>
      <td>2.000000</td>
      <td>2.000000</td>
      <td>16.000000</td>
      <td>7860.000000</td>
      <td>0.000000</td>
      <td>5.000000e+04</td>
      <td>26.442308</td>
    </tr>
    <tr>
      <th>max</th>
      <td>2013.000000</td>
      <td>56.000000</td>
      <td>64.000000</td>
      <td>2.000000</td>
      <td>4.000000</td>
      <td>18.000000</td>
      <td>9590.000000</td>
      <td>3.000000</td>
      <td>1.259999e+06</td>
      <td>294610.968750</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p><code>describe</code> returns a dataframe with the same columns as the source dataframe. For numeric data, the result’s index will include count, mean, std, min, max as well as lower, 50 and upper percentiles. By default the lower percentile is 25 and the upper percentile is 75. The 50 percentile is the same as the median. “incwage” is the annual income variable. Because values are generally in the tens of thousands, Python displays this using scientific notation (e.g.&nbsp;3.442870e+05). This is pretty ugly, so let’s create a new variable called “income” which divides that number by 1000 to make it more manageable:</p>
<div class="cell" data-outputid="9916c0fc-2ef4-4a91-a59d-e47f02969b64" data-execution_count="5">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'income'</span>]<span class="op">=</span>df[<span class="st">'incwage'</span>]<span class="op">/</span><span class="dv">1000</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df[<span class="st">'income'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0         14.20
1         17.68
2         28.00
3         27.50
4         17.00
          ...  
344282    17.00
344283     3.20
344284    13.00
344285     8.80
344286    15.00
Name: income, Length: 344287, dtype: float64</code></pre>
</div>
</div>
<section id="exercise" class="level3">
<h3 class="anchored" data-anchor-id="exercise">Exercise</h3>
<p>Given these summary statistics, answer the following questions:</p>
<ol type="1">
<li>what is the median hourly wage?</li>
<li>what is the average age?</li>
<li>are there more men or women?</li>
<li>intepret the mean of the “race” column.</li>
</ol>
<p>The answer to the last question should provoke some futher thought; the race column is categorical, but because it contains numbers it’s being treated as numerical. The mean of a categorical variable is meaningless; For object data (e.g.&nbsp;categories, strings or timestamps), the result’s index will include count, unique, top, and freq. The top is the most common value. The freq is the most common value’s frequency. Timestamps also include the first and last items.</p>
<p>Let’s convert the race column from a numerical variable into a categorical one, and try <code>describe</code> once again:</p>
<div class="cell" data-outputid="7fa93b7f-5807-435f-c0be-e23ba21364f9" data-execution_count="6">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>df.dtypes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>year            int64
state           int64
age             int64
sex             int64
race            int64
sch           float64
ind             int64
union         float64
incwage       float64
realhrwage    float64
occupation     object
income        float64
dtype: object</code></pre>
</div>
</div>
<div class="cell" data-outputid="9643b377-f49d-4376-a008-06a9432db860" data-execution_count="7">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'race'</span>]<span class="op">=</span>df[<span class="st">'race'</span>].astype(<span class="st">'category'</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'race'</span>].describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>count     344287
unique         4
top            1
freq      240382
Name: race, dtype: int64</code></pre>
</div>
</div>
<p>what other variables are categorical? Convert them to categorical and describe. What is the most common occupation in this dataset?</p>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># convert the variables to categorical and describe</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>These statistics are useful, but suppose we want detailed counts of the number of individuals in each category; For this, we can use the <code>groupby</code> function, with the <code>.size()</code> operator which simply counts the number of rows in each category.</p>
<div class="cell" data-outputid="9f1abc21-9bf0-47d7-894f-fcacb8765828" data-execution_count="9">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>occupations<span class="op">=</span> df.groupby(<span class="st">'occupation'</span>).size()</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>occupations.sort_values(ascending<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>occupation
.                                         132708
Office and Admin Support                   50635
Managers                                   35696
Consruction, Extraction, Installation      30579
Production                                 29732
Transportation and materials moving        21277
Computer and Math Technicians               8602
Protective Service adj_occupations          7809
financial Operators                         7702
Business Operators                          7327
Community and Social Workers                6025
Lawyers, Judges,Physicans and dentists      3835
Farming, Fishing &amp; Forestry                 2360
dtype: int64</code></pre>
</div>
</div>
<p>What is the most common profession?</p>
</section>
</section>
<section id="distributions" class="level1">
<h1>Distributions</h1>
<p>Now that we’ve cleaned our data up, let’s have a closer look at the <em>distribution</em> of our data. The best way to do this is using a histogram, which takes one variable and divides its values into a number of bins shown on the X axis, and then counts the number of observations in each of those bins on the Y axis. Let’s start by looking at the distribution of the <code>income</code> variable:</p>
<div class="cell" data-outputid="a8c0171e-bfc2-49cf-ad50-019a302f8ff9" data-execution_count="10">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>df<span class="op">=</span>df[df[<span class="st">'year'</span>]<span class="op">==</span><span class="dv">2013</span>] <span class="co"># filter the dataframe to only contain 2013 data</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>plt.hist(df[<span class="st">'income'</span>]) <span class="co"># plot a histogram of the income variable</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>plt.show() <span class="co"># show the plot</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="W07. Distributions and Basic Statistics_files/figure-html/cell-11-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>This is a pretty ugly histogram, and it’s not telling us very much useful information. It shows that the vast majority of people make between 0 and $100,000 per year, and a few make over 200k. A small number make over $1 million per year, so the plot is being extended to accomodate these outliers. Let’s try fixing the histogram up a bit.</p>
<div class="cell" data-outputid="dc491133-f7ac-424b-f427-28ed1514e295" data-execution_count="11">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>plt.hist(df[<span class="st">'income'</span>], bins<span class="op">=</span><span class="dv">100</span>, edgecolor<span class="op">=</span><span class="st">'white'</span>, density<span class="op">=</span><span class="va">True</span>) </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># i've increased the number of bins to 100 to make the plot smoother,</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># added the density=True argument to make the y-axis a probability density instead of a count,</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># and the edgecolor='white' argument to add some space between the bars, making the plot easier to read</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Income ($, thousands)'</span>) <span class="co"># add a label to the x axis</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"U.S. Income Distributon, 2013"</span>) <span class="co"># add a title to the plot</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>plt.show() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="W07. Distributions and Basic Statistics_files/figure-html/cell-12-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>That’s better. We can now see more variation in how much people earn within the $0-200,000 range since we increased the number of bins in the histogram. It could still be improved, though. The outliers making over $ 1 million are creating lots of dead space in this plot. We can defensibly omit them from the plot, as long as we acknowledge that we’ve done this somewhere in our analysis.</p>
<p>Let’s also plot the mean and median of our distribution.</p>
<div class="cell" data-outputid="ec9bc59c-b61b-4c2b-c3fc-35a45f3bf7db" data-execution_count="12">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>inc_summary<span class="op">=</span>df[<span class="st">'income'</span>].describe() <span class="co"># get summary statistics for the income variable using the describe() method, and store them in a variable called inc_summary</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(inc_summary[[<span class="st">'mean'</span>,<span class="st">'50%'</span>,<span class="st">'std'</span>]]) <span class="co"># print the mean, median and standard deviation</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>plt.hist(df[<span class="st">'income'</span>], bins<span class="op">=</span><span class="dv">100</span>, edgecolor<span class="op">=</span><span class="st">'white'</span>, density<span class="op">=</span><span class="va">True</span>) <span class="co"># plot the histogram again</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>plt.axvline(inc_summary[<span class="st">'mean'</span>], color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'dashed'</span>, linewidth<span class="op">=</span><span class="dv">1</span>,label<span class="op">=</span><span class="st">'Mean'</span>) <span class="co"># get the mean from the inc_summary variable and plot a vertical line in red at that point</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>plt.axvline(inc_summary[<span class="st">'50%'</span>], color<span class="op">=</span><span class="st">'black'</span>, linestyle<span class="op">=</span><span class="st">'dashed'</span>, linewidth<span class="op">=</span><span class="dv">1</span>, label<span class="op">=</span><span class="st">'Median'</span>) <span class="co"># do the same for the median, but plot it in black</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Income ($, thousands'</span>)</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"U.S. Income Distributon, 2013"</span>)</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>plt.xlim(<span class="dv">0</span>,<span class="dv">250</span>) <span class="co"># set the x-axis limits to 0 to 250-- this will get rid of the outliers on the right side of the plot</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>mean    51.821863
50%     40.000000
std     60.163449
Name: income, dtype: float64</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="W07. Distributions and Basic Statistics_files/figure-html/cell-13-output-2.png" class="img-fluid"></p>
</div>
</div>
<p>This histogram is far more informative– use the questions in the exercise below to guide your interpretation of this plot.</p>
<section id="exercise-1" class="level3">
<h3 class="anchored" data-anchor-id="exercise-1">Exercise</h3>
<ol type="1">
<li>What is the (approximate) mean of this distribution?</li>
<li>What is the median?</li>
<li>Keeping in mind that we’ve excluded some extreme values, why might the mean be larger than the median? Intepret this qualitatively in reference to income inequality.</li>
<li>There are slight bumps in density at $100,000, $150,000, $200,000, and $250,000. Why might this be?</li>
</ol>
<p>As we have seen, there are a few extreme outliers in the income distribution (really rich people). Outliers can bias some statistical tests, so for the rest of this workbook, we’re going to subset our dataframe to exclude those who make over $200k per year:</p>
<div class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>df<span class="op">=</span>df[df[<span class="st">'income'</span>]<span class="op">&lt;</span><span class="dv">200</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="functions" class="level2">
<h2 class="anchored" data-anchor-id="functions">Functions</h2>
<p>Now we’ve got a pretty good sense of what’s going on with the income variable. But suppose we want to do this for another variable. We could just copy and paste the code above, switch around the variable in question, and edit the labels. But there’s a far more efficient way of doing things. In Python and most programming languages, you can write your own <strong>function</strong>.</p>
<p>A function is a block of code that you can call on to do a specific task. You can write your own functions, or you can use functions that other people have written. Functions are useful because they allow you to write code once, and then call on it whenever you need it. This is much more efficient than writing the same code over and over again. You can define a function by using the <code>def</code> keyword. For example, we can define a function called <code>variable_stats</code> that will calculate the mean, median, and standard deviation of the variable tha you specify.</p>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> variable_stats(variable): <span class="co"># define a function called variable_stats that takes a variable as an argument</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>    mean <span class="op">=</span> variable.mean() <span class="co"># calculate the mean of the variable</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    median <span class="op">=</span> variable.median() <span class="co"># calculate the median of the variable</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    std <span class="op">=</span> variable.std() <span class="co"># calculate the standard deviation of the variable</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Mean: "</span> <span class="op">+</span> <span class="bu">str</span>(mean)) <span class="co"># print the mean</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Median: "</span> <span class="op">+</span> <span class="bu">str</span>(median)) <span class="co"># print the median</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Standard deviation: "</span> <span class="op">+</span> <span class="bu">str</span>(std)) <span class="co"># print the standard deviation</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We can then call on this function whenever we want to calculate these statistics. </span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>variable_stats(df[<span class="st">'income'</span>]) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Mean: 46.75408852483797
Median: 40.0
Standard deviation: 32.82190958000738</code></pre>
</div>
</div>
<p>Now, to calculate the same values for the age variable, we can simply change which variable we feed the function:</p>
<div class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>variable_stats(df[<span class="st">'age'</span>]) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Mean: 42.845076809704665
Median: 43.0
Standard deviation: 10.576333292267508</code></pre>
</div>
</div>
<p>We can write a more complex function to deal with plotting new histograms for different variables, since most of the code we need to plot a histogram won’t change from one variable to the next. A few things will change– the variable that we’re plotting, the title of the graph, and the labels on the x and y axes, and perhaps the number of bins. We can write a function called <code>plot_histogram</code> that takes these four things as arguments, and then plots a histogram. Then, we can call on this function whenever we want to plot a histogram of a new variable. Below is the same code we used to plot the histogram of income, but this time we’ve written it as a function called <code>plot_histogram</code> and substituted the variable name <code>income</code> for the argument <code>variable</code>.</p>
<div class="cell" data-outputid="b4159584-f642-4ef8-9a8a-818d3edef12e" data-execution_count="17">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_histogram(variable, bin_number, xlab, title): <span class="co"># define a function called plot_histogram that takes a variable, number of bins, x-axis label, and title as arguments</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    summary<span class="op">=</span>variable.describe()     </span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    plt.hist(variable, bins<span class="op">=</span>bin_number,edgecolor<span class="op">=</span><span class="st">'white'</span>, density<span class="op">=</span><span class="va">True</span>) <span class="co"># plot the histogram. Notice i've changed "bins=100" to "bins=bin_number" so that the number of bins can be specified when the function is called</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>    plt.axvline(summary[<span class="st">'mean'</span>], color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'dashed'</span>, linewidth<span class="op">=</span><span class="dv">1</span>,label<span class="op">=</span><span class="st">'Mean '</span><span class="op">+</span><span class="bu">str</span>(<span class="bu">round</span>(summary[<span class="st">'mean'</span>],<span class="dv">2</span>)))</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    plt.axvline(summary[<span class="st">'50%'</span>], color<span class="op">=</span><span class="st">'black'</span>, linestyle<span class="op">=</span><span class="st">'dashed'</span>, linewidth<span class="op">=</span><span class="dv">1</span>, label<span class="op">=</span><span class="st">'Median '</span><span class="op">+</span><span class="bu">str</span>(<span class="bu">round</span>(summary[<span class="st">'50%'</span>],<span class="dv">2</span>)))</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>    plt.legend()</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>    plt.xlabel(xlab) <span class="co"># i've changed the x-axis label to "xlab" so that it can be specified when the function is called</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>    plt.title(title) <span class="co"># similarly, we can now specify the title when calling the function</span></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>    plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we can just call the function with the variable we want to plot, the number of bins, the x-axis label, and the title using one line of code. Let’s recreate the histogram of income from above, but this time using the function we just defined:</p>
<div class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>plot_histogram(variable <span class="op">=</span> df[<span class="st">'income'</span>], bin_number <span class="op">=</span> <span class="dv">20</span>, xlab <span class="op">=</span> <span class="st">'Income ($, 000)'</span>, title <span class="op">=</span> <span class="st">'U.S. Income Distribution, 2013'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="W07. Distributions and Basic Statistics_files/figure-html/cell-19-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>If we want to produce lots of similar plots, this really helps us cut down on repetition.</p>
<section id="exercise-2" class="level3">
<h3 class="anchored" data-anchor-id="exercise-2">Exercise</h3>
<ol type="1">
<li>Plot the histogram of the ‘age’ variable with 80 bins, label the x-axis “Age”, and add title of ‘U.S. Age Distribution, 2013’.</li>
<li>Plot the distribution of schooling years.
<ul>
<li>Find an appropriate number of bins</li>
<li>Label it clearly</li>
<li>Interpret salient trends</li>
</ul></li>
</ol>
</section>
</section>
<section id="the-central-limit-theorem" class="level2">
<h2 class="anchored" data-anchor-id="the-central-limit-theorem">The Central Limit Theorem</h2>
<p>But as we learned in class, the Central Limit Theorem states that the <strong>distribution of the mean of a sample of observations will be approximately normal, regardless of the distribution of the original observations</strong>. So, if we take a <strong>large enough sample</strong> of observations from each of these variables, and calculate the mean of each sample, we should get a normal distribution. This is important because the normal distribution behaves in a very predictable way.</p>
<p>The code below creates a “standard normal” distribution with a mean of 0 and a standard deviation of 1:</p>
<div class="cell" data-outputid="c9cde8cf-1864-4add-f2ff-457acd7f9828" data-execution_count="19">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>mu, se<span class="op">=</span> <span class="dv">0</span>, <span class="dv">1</span> <span class="co"># create two variables, a mean "mu" equal to zero, and standard deviation "se" equal to 1</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.linspace(mu <span class="op">-</span> <span class="dv">3</span><span class="op">*</span>se, mu <span class="op">+</span> <span class="dv">3</span><span class="op">*</span>se, <span class="dv">100</span>) <span class="co"># create a range of values from -3 to 3 standard deviations</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>plt.plot(x, norm.pdf(x, mu, se)) <span class="co"># plot the normal distribution</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>plt.axvline(mu, color<span class="op">=</span><span class="st">'black'</span>, linestyle<span class="op">=</span><span class="st">'solid'</span>, linewidth<span class="op">=</span><span class="dv">1</span>,label<span class="op">=</span><span class="st">'µ'</span>)  <span class="co"># plot a vertical line at the mean</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>plt.axvline(mu<span class="op">-</span>se<span class="op">*</span><span class="dv">2</span>, color<span class="op">=</span><span class="st">'black'</span>, linestyle<span class="op">=</span><span class="st">'dashed'</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>,label<span class="op">=</span><span class="st">'µ ± 2σ'</span>) <span class="co"># plot a vertical line at the mean plus 2 standard deviations</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>plt.axvline(mu<span class="op">+</span>se<span class="op">*</span><span class="dv">2</span>, color<span class="op">=</span><span class="st">'black'</span>, linestyle<span class="op">=</span><span class="st">'dashed'</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>)  <span class="co"># plot a vertical line at the mean minus 2 standard deviations</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="W07. Distributions and Basic Statistics_files/figure-html/cell-22-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>for a distribution with this shape,</p>
<pre><code>* 68% of the values will be within 1 standard deviation of the mean
* 95.45% of the values will be within 2 standard deviations of the mean
* 99.7% of the values will be within 3 standard deviations of the mean</code></pre>
<p>so in the plot above, if I took a random value from the distribution, there’s a 95% chance that it would be between -2 and 2 (within the dotted lines), and a 99.7% chance that it would be between -3 and 3.</p>
<p>It’s crucial to note, however, that this applies to the mean of a sample, not individual observations. For example, this doesnt mean that there is a 95% chance that an individual taken at random will have an income that is within 2 standard deviations of the mean ($46k). It means that if we take a sample of 100 observations, there is a 95% chance that the <strong>mean of that sample</strong> will be within 2 standard deviations of the mean ($46k).</p>
<section id="sampling" class="level3">
<h3 class="anchored" data-anchor-id="sampling">Sampling</h3>
<p>To illustrate how this works, for the rest of this workshop we’re going to pretend that the dataframe contains the entire adult <strong>population</strong> of the United States (of course, it is actually a sample but just pretend). The mean of this distribution will thus be the <strong>population mean</strong>; for the income variable, this is $46k.</p>
<p>We can use the <code>sample</code> function to take a random sample of observations from a distribution. We’ll take a sample of 5 observations from the income variable and use the <code>mean</code> function to calculate the mean of this sample.</p>
<div class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>income_sample <span class="op">=</span> df[<span class="st">'income'</span>].sample(<span class="dv">5</span>, replace<span class="op">=</span><span class="va">True</span>) <span class="co"># take a random sample of 10 observations from the income variable</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>income_sample_mean<span class="op">=</span>income_sample.mean() <span class="co"># calculate the mean of the sample</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Mean: "</span> <span class="op">+</span> <span class="bu">str</span>(income_sample_mean)) <span class="co"># print the sample mean</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Mean: 38.3604</code></pre>
</div>
</div>
</section>
<section id="exercise-3" class="level3">
<h3 class="anchored" data-anchor-id="exercise-3">Exercise</h3>
<ol type="1">
<li>Run the code cell above 10 times and make note of the mean. What is the farthest the sample mean deviates from the “population” mean of $51k?</li>
<li>Increase the sample size from 5 to 100 and run the cell 10 more times. Now, what is the farthest the sample mean deviates from the population mean?</li>
<li>Increase the sample size to 1000. What do you notice about the sample means as we increase the sample size?</li>
</ol>
<p>Hopefully, you will have noticed that as the sample size increases, the sample means tend to be closer to the population mean. But clicking that cell is hard work. Let’s create a loop that will run that block of code 10000 times, save the sample means in a list, and plot the distribution of sample means as a histogram. Once again, we’ll start by only drawing samples of 10 observations:</p>
<div class="cell" data-execution_count="38">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create an empty list to store sample means</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>sample_means<span class="op">=</span>[]</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>sample_size<span class="op">=</span><span class="dv">10</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="co"># loop 10,000 times.</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>,<span class="dv">10000</span>):</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>    sample<span class="op">=</span> df[<span class="st">'income'</span>].sample(sample_size, replace<span class="op">=</span><span class="va">True</span>) <span class="co"># draw a sample of 10 observations from the income variable, with replacement</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>    sample_mean<span class="op">=</span>sample.mean() <span class="co"># calculate the mean of the sample</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>    sample_means.append(sample_mean) <span class="co"># append the sample mean to the list of sample means</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>plt.hist(sample_means, bins<span class="op">=</span><span class="dv">30</span>, edgecolor<span class="op">=</span><span class="st">'white'</span>, density<span class="op">=</span><span class="va">True</span>) <span class="co"># plot a histogram of the sample means</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Distribution of Sample Means (n=</span><span class="sc">{}</span><span class="st">)'</span>.<span class="bu">format</span>(sample_size)) <span class="co"># add a title</span></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="W07. Distributions and Basic Statistics_files/figure-html/cell-24-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="exercise-4" class="level3">
<h3 class="anchored" data-anchor-id="exercise-4">Exercise</h3>
<pre><code>1. Edit the code block above so that instead of drawing samples of 10 observations, it draws samples of 1000 observations
2. What happens to the distribution?</code></pre>
<p>When we draw 10,000 samples of 1000 observations each, the distribution of sample means looks a lot more normally distributed than the underlying distribution of income itself, which is skewed to the right. To show how normally distributed it is, let’s overlay the normal distribution line we plotted earlier and fit it to the distribution of sample means. We’ll start off by making the same histogram of sample means, but add a line plot of the normal distribution and some droplines at ± 2 standard deviations.</p>
<p>Because we may want to do this for several different variables, let’s once again package our code as a function in which we can swap around a couple bits. In this case, we may want to swap around the variable we’re plotting, the label on the x-axis, and the size of the samples we’re drawing. So we’ll create a function called <code>plot_sample_means</code> that takes these three things as arguments (<code>var</code>, <code>xlab</code>, and <code>sample_size</code>).</p>
<div class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_sample_means(var, xlab, sample_size): <span class="co"># define a function called plot_sample_means that takes a variable, x-axis label, and sample size as arguments</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>    <span class="co">#create an empty list to store sample means</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>    sample_means<span class="op">=</span>[]</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># loop 10,000 times.</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>,<span class="dv">10000</span>):</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>        <span class="co"># for each iteration, draw a sample of the size specified by the "sample_size" parameter</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>        sample<span class="op">=</span>var.sample(sample_size, replace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>        <span class="co"># calculate the mean, and append it to the list of sample means. </span></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>        sample_mean<span class="op">=</span>sample.mean()</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>        sample_means.append(sample_mean)</span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># now, plot a histogram </span></span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>    plt.hist(sample_means, color<span class="op">=</span><span class="st">'blue'</span>,alpha<span class="op">=</span><span class="fl">0.5</span>, bins<span class="op">=</span><span class="bu">int</span>(<span class="dv">30</span>), edgecolor<span class="op">=</span><span class="st">'white'</span>, density<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a>    <span class="co"># fit a normal distribution to the data </span></span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a>    mu, se <span class="op">=</span> norm.fit(sample_means)</span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a>    xmin, xmax <span class="op">=</span> plt.xlim()</span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> np.linspace(xmin, xmax, <span class="dv">100</span>)</span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a>    p <span class="op">=</span> norm.pdf(x, mu, se) </span>
<span id="cb34-22"><a href="#cb34-22" aria-hidden="true" tabindex="-1"></a>    plt.plot(x, p, <span class="st">'k'</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb34-23"><a href="#cb34-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-24"><a href="#cb34-24" aria-hidden="true" tabindex="-1"></a>    <span class="co"># calculate the difference between the mean of the sample means </span></span>
<span id="cb34-25"><a href="#cb34-25" aria-hidden="true" tabindex="-1"></a>    diff<span class="op">=</span><span class="bu">abs</span>(mu<span class="op">-</span>var.mean())</span>
<span id="cb34-26"><a href="#cb34-26" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb34-27"><a href="#cb34-27" aria-hidden="true" tabindex="-1"></a>    <span class="co"># add droplines, labels, title, legend, and limit the x-axis range to 3 standard deviations from the mean on either side.</span></span>
<span id="cb34-28"><a href="#cb34-28" aria-hidden="true" tabindex="-1"></a>    plt.axvline(mu, color<span class="op">=</span><span class="st">'green'</span>, linestyle<span class="op">=</span><span class="st">'solid'</span>, linewidth<span class="op">=</span><span class="dv">3</span>,label<span class="op">=</span><span class="st">'µx̄='</span><span class="op">+</span><span class="bu">str</span>(<span class="bu">round</span>(mu, <span class="dv">3</span>)))</span>
<span id="cb34-29"><a href="#cb34-29" aria-hidden="true" tabindex="-1"></a>    plt.axvline(mu<span class="op">-</span>se<span class="op">*</span><span class="dv">2</span>, color<span class="op">=</span><span class="st">'black'</span>, linestyle<span class="op">=</span><span class="st">'dashed'</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>,label<span class="op">=</span><span class="st">'µ ± 2σ'</span>)</span>
<span id="cb34-30"><a href="#cb34-30" aria-hidden="true" tabindex="-1"></a>    plt.axvline(mu<span class="op">+</span>se<span class="op">*</span><span class="dv">2</span>, color<span class="op">=</span><span class="st">'black'</span>, linestyle<span class="op">=</span><span class="st">'dashed'</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>)</span>
<span id="cb34-31"><a href="#cb34-31" aria-hidden="true" tabindex="-1"></a>    plt.legend()</span>
<span id="cb34-32"><a href="#cb34-32" aria-hidden="true" tabindex="-1"></a>    plt.xlabel(xlab)    </span>
<span id="cb34-33"><a href="#cb34-33" aria-hidden="true" tabindex="-1"></a>    plt.title(<span class="st">'Distribution of Sample Means (n=</span><span class="sc">{}</span><span class="st">)'</span>.<span class="bu">format</span>(sample_size))</span>
<span id="cb34-34"><a href="#cb34-34" aria-hidden="true" tabindex="-1"></a>    plt.xlim(mu<span class="op">-</span>se<span class="op">*</span><span class="dv">3</span>, mu<span class="op">+</span>se<span class="op">*</span><span class="dv">3</span>)</span>
<span id="cb34-35"><a href="#cb34-35" aria-hidden="true" tabindex="-1"></a>    plt.show()  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>plot_sample_means(df[<span class="st">'income'</span>], xlab<span class="op">=</span><span class="st">'Income, ($, 000)'</span>, sample_size<span class="op">=</span><span class="dv">1000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="W07. Distributions and Basic Statistics_files/figure-html/cell-26-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>We can see that the distribution of sample means (for samples of 1000 people) very closely approximates the normal distribution. The addition of droplines at ±2σ tells us that <strong>if we take a random sample of 1000 people, there is a 95% chance that the mean of this sample will fall between ~$44.7k and ~$48.8k</strong>.</p>
<p>Why is this important? let’s see what happens when we filter the sample based on peoples’ attributes. The code below creates two dataframes: one called <code>men</code> which only contains male respondents, and one called <code>women</code> which only contains female respondents. Then, we run the <code>plot_sample_means()</code> function on each of these dataframes.</p>
<div class="cell" data-execution_count="40">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>men<span class="op">=</span>df[df[<span class="st">'sex'</span>]<span class="op">==</span><span class="dv">1</span>][<span class="st">'income'</span>] <span class="co"># create a new dataframe containing only income values for men</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>women<span class="op">=</span>df[df[<span class="st">'sex'</span>]<span class="op">==</span><span class="dv">2</span>][<span class="st">'income'</span>] <span class="co"># create a new dataframe containing only income values for women</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>plot_sample_means(men, xlab<span class="op">=</span><span class="st">'Income, ($, 000)'</span>, sample_size<span class="op">=</span><span class="dv">500</span>)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>plot_sample_means(women, xlab<span class="op">=</span><span class="st">'Income, ($, 000)'</span>, sample_size<span class="op">=</span><span class="dv">500</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="W07. Distributions and Basic Statistics_files/figure-html/cell-27-output-1.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="W07. Distributions and Basic Statistics_files/figure-html/cell-27-output-2.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="exercise-5" class="level3">
<h3 class="anchored" data-anchor-id="exercise-5">Exercise</h3>
<pre><code>1. These two histograms may look the same, but look closely at the values. 
2. The population mean income for women is around $39.6k. Based on the histogram of sample means taken from only men, 
    * What is the likelihood of observing a sample mean of $39.6k among men due to random chance?
3. Interpret this finding qualitatively.</code></pre>
<p>The plot of incomes for men and women show very different distributions, but they look quite similar. To make this more readable, let’s define one last function that can take two or more groups and plot the distribution of their sample means on the same plot:</p>
<div class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> two_hist(groups,group_labs,xlab, title): <span class="co"># define a function called two_hist that takes a list of groups, a list of group labels, an x-axis label, and a title as arguments</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>        plt.figure(figsize<span class="op">=</span>(<span class="dv">15</span>,<span class="dv">6</span>)) <span class="co"># set the figure size</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>        it<span class="op">=-</span><span class="dv">1</span> <span class="co"># create a counter variable called "it" and set it equal to -1</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> var <span class="kw">in</span> groups: <span class="co"># loop through each group in the list of groups</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>            it<span class="op">+=</span><span class="dv">1</span> <span class="co"># increase the iterator by 1</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>            sample_size<span class="op">=</span><span class="dv">1000</span> <span class="co"># set the sample size equal to 1000</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>            sample_means<span class="op">=</span>[] <span class="co"># create an empty list to store sample means</span></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>            iterations<span class="op">=</span><span class="dv">10000</span> <span class="co"># set the number of iterations equal to 10,000</span></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>            <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>,iterations): <span class="co"># loop through the number of iterations</span></span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>                sample<span class="op">=</span>var.sample(sample_size, replace<span class="op">=</span><span class="va">True</span>) <span class="co"># draw a sample of the size specified by the "sample_size" parameter</span></span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>                sample_mean<span class="op">=</span>sample.mean() <span class="co"># calculate the mean of the sample</span></span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>                sample_means.append(sample_mean) <span class="co"># append the sample mean to the list of sample means</span></span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a>            </span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a>            plt.hist(sample_means, bins<span class="op">=</span><span class="bu">int</span>(iterations<span class="op">/</span><span class="dv">300</span>),edgecolor<span class="op">=</span><span class="st">'white'</span>,density<span class="op">=</span><span class="va">True</span>, label<span class="op">=</span>group_labs[it])  <span class="co"># plot a histogram of the sample means</span></span>
<span id="cb38-18"><a href="#cb38-18" aria-hidden="true" tabindex="-1"></a>            mu, se <span class="op">=</span> norm.fit(sample_means) <span class="co"># fit a normal distribution to the data</span></span>
<span id="cb38-19"><a href="#cb38-19" aria-hidden="true" tabindex="-1"></a>            xmin, xmax <span class="op">=</span> plt.xlim() <span class="co"># set the x-axis limits</span></span>
<span id="cb38-20"><a href="#cb38-20" aria-hidden="true" tabindex="-1"></a>            x <span class="op">=</span> np.linspace(xmin, xmax, <span class="dv">100</span>) <span class="co"># create a range of values from the minimum to the maximum x-axis value</span></span>
<span id="cb38-21"><a href="#cb38-21" aria-hidden="true" tabindex="-1"></a>            p <span class="op">=</span> norm.pdf(x, mu, se) <span class="co"># calculate the probability density function for the normal distribution</span></span>
<span id="cb38-22"><a href="#cb38-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-23"><a href="#cb38-23" aria-hidden="true" tabindex="-1"></a>            plt.plot(x, p, <span class="st">'k'</span>, linewidth<span class="op">=</span><span class="dv">2</span>) <span class="co"># plot the normal distribution</span></span>
<span id="cb38-24"><a href="#cb38-24" aria-hidden="true" tabindex="-1"></a>            plt.xlabel(xlab) <span class="co"># add an x-axis label</span></span>
<span id="cb38-25"><a href="#cb38-25" aria-hidden="true" tabindex="-1"></a>            plt.title(title) <span class="co"># add a title</span></span>
<span id="cb38-26"><a href="#cb38-26" aria-hidden="true" tabindex="-1"></a>            plt.axvline(var.mean(), color<span class="op">=</span><span class="st">'green'</span>, linestyle<span class="op">=</span><span class="st">'solid'</span>, linewidth<span class="op">=</span><span class="dv">3</span>) <span class="co"># add a vertical line at the mean of the variable</span></span>
<span id="cb38-27"><a href="#cb38-27" aria-hidden="true" tabindex="-1"></a>            plt.axvline(mu<span class="op">-</span>se<span class="op">*</span><span class="dv">2</span>, color<span class="op">=</span><span class="st">'black'</span>, linestyle<span class="op">=</span><span class="st">'dashed'</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>)</span>
<span id="cb38-28"><a href="#cb38-28" aria-hidden="true" tabindex="-1"></a>            plt.axvline(mu<span class="op">+</span>se<span class="op">*</span><span class="dv">2</span>, color<span class="op">=</span><span class="st">'black'</span>, linestyle<span class="op">=</span><span class="st">'dashed'</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>)</span>
<span id="cb38-29"><a href="#cb38-29" aria-hidden="true" tabindex="-1"></a>            plt.legend() <span class="co"># add a legend</span></span>
<span id="cb38-30"><a href="#cb38-30" aria-hidden="true" tabindex="-1"></a>            </span>
<span id="cb38-31"><a href="#cb38-31" aria-hidden="true" tabindex="-1"></a>        plt.show()  <span class="co"># show the plot </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>two_hist([men,women],[<span class="st">'Men'</span>,<span class="st">'Women'</span>],<span class="st">'Income ($, thousands)'</span>, <span class="st">"Income Sample Means"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="W07. Distributions and Basic Statistics_files/figure-html/cell-29-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>There we have it: A stark, quantitative representation of the gender wage gap.</p>
<p>If we simply compared the means between a sample of women and a sample of men, the best we could do in terms of inference would be to say something like “the average income for men was $14.2k higher than it was for women.” Though this is an important finding, the central limit theorem lets us add important context.</p>
<pre><code>1. We took 10,000 large samples of men and calculated the means of each sample.
2. We found that over 99.7% of them were greater than $50,000. 
3. We took 10,000 large samples of women and calculated the means of each sample.
4. We found that over 99.7% of them were smaller than $44,000.</code></pre>
<p>The fact that the distribution of income sample means between men and women do not overlap at all tells us that the probability of this variation in incomes being due to random chance is extremely, extremely small. Thus, we can say that the observed difference in income between men and women is <strong>statistically significant</strong>.</p>
</section>
<section id="extension" class="level3">
<h3 class="anchored" data-anchor-id="extension">Extension</h3>
<p>Given that we’ve used functions to create these plots, we can make plots with different data relatively easily. Intersectionality is an important consideration when thinking about inequality. The code below allows you to create a subset of income for white men:</p>
<p><code>w_men=df[(df['sex']==1)&amp;(df['race']==1)]['income']</code></p>
<p>There is a strong gendered difference in income, but what about the effects of both race and gender? How does union membership mitigate these inequalities? What if we only compare people in the same types of jobs? Try creating subsets based on these characteristics and plotting distributions of sample means to answer these questions.</p>
</section>
</section>
<section id="confidence-intervals" class="level2">
<h2 class="anchored" data-anchor-id="confidence-intervals">Confidence Intervals</h2>
<p>So far in this workshop, we’ve had the luxury of being able to draw many random samples and plot the distributions of their sample means to infer the population mean. The Central Limit Theorem lets us assume that these sample means are normally distributed, and consequently that there is a 95.45% chance that the <strong>population mean</strong> within two standard errors of the <strong>sample mean</strong>. This allows us to make inferences on the basis of <em>a single sample</em>. The standard error is the</p>
<section id="sample-standard-deviation" class="level3">
<h3 class="anchored" data-anchor-id="sample-standard-deviation">Sample Standard Deviation</h3>
<p><span class="math display">\[\huge s = \sqrt{\frac{1}{n-1} \sum_{i=1}^n (x_i - \overline{x})^2}\]</span></p>
</section>
<section id="standard-error" class="level3">
<h3 class="anchored" data-anchor-id="standard-error">Standard Error</h3>
<p><span class="math display">\[\huge se = \frac{s}{\sqrt{n}}\]</span></p>
<p>Given a large enough sample <span class="math inline">\(x\)</span>, we can build a 95% confidence interval as follows:</p>
<p><span class="math display">\[ \huge 95\% CI = \overline{x} \pm (1.96 \times se)\]</span></p>
<p>Let’s draw a sample of 1000 random individuals from our data, and compute a 95% confidence interval to estimate the population mean for income. We’ll begin by creating a swarmplot to get a sense of how the data are distributed.</p>
<div class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>sample<span class="op">=</span>df.sample(<span class="dv">1000</span>) <span class="co"># draw a random sample of 1000 observations from the dataframe</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>sns.swarmplot(data <span class="op">=</span> sample, y<span class="op">=</span><span class="st">'income'</span>) <span class="co"># plot a swarmplot of income</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Income Distribution'</span>) <span class="co"># add a title</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="27">
<pre><code>Text(0.5, 1.0, 'Income Distribution')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="W07. Distributions and Basic Statistics_files/figure-html/cell-31-output-2.png" class="img-fluid"></p>
</div>
</div>
<p>Now let’s set about calculating the 95% confidence interval and plotting it on our swarmplot. Luckily, the components we need to this are easy to calculate. We just need the mean, standard deviation, and number of observations. All of these are provided by the <code>.describe()</code> function, which calculates summary statistics for a sample.</p>
<div class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>desc<span class="op">=</span>sample[<span class="st">'income'</span>].describe() <span class="co"># calculate descriptive statistics for the sample</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(desc) <span class="co"># print the descriptive statistics</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>count    1000.000000
mean       46.862772
std        32.960154
min         0.500000
25%        23.000000
50%        40.000000
75%        63.000000
max       189.000000
Name: income, dtype: float64</code></pre>
</div>
</div>
<p>From the set of descriptive statistics, we can pull out the relevant components, calculate the standard error, and create a 95% confidence interval as follows:</p>
<div class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>mean<span class="op">=</span>desc[<span class="st">'mean'</span>] <span class="co"># set the mean equal to a variable called "mean"</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>std<span class="op">=</span>desc[<span class="st">'std'</span>] <span class="co"># set the standard deviation equal to a variable called "std"</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>n<span class="op">=</span>desc[<span class="st">'count'</span>] <span class="co"># set the sample size equal to a variable called "n"</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>se<span class="op">=</span>std<span class="op">/</span>np.sqrt(n) <span class="co"># calculate the standard error of the mean</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'The mean is'</span>, <span class="bu">round</span>(mean, <span class="dv">2</span>), <span class="st">'with a standard error of'</span>, <span class="bu">round</span>(se, <span class="dv">2</span>)) <span class="co"># print the mean and standard error</span></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>upper_ci <span class="op">=</span> mean<span class="op">+</span>se<span class="op">*</span><span class="fl">1.96</span> <span class="co"># calculate the upper confidence interval</span></span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>lower_ci <span class="op">=</span> mean<span class="op">-</span>se<span class="op">*</span><span class="fl">1.96</span> <span class="co"># calculate the lower confidence interval</span></span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'The 95</span><span class="sc">% c</span><span class="st">onfidence interval is'</span>, <span class="bu">round</span>(lower_ci, <span class="dv">2</span>), <span class="st">'to'</span>, <span class="bu">round</span>(upper_ci, <span class="dv">2</span>)) <span class="co"># print the confidence interval</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The mean is 46.86 with a standard error of 1.04
The 95% confidence interval is 44.82 to 48.91</code></pre>
</div>
</div>
<p>Finally, let’s plot these bounds on our swarmplot to graphically show this range. We can now claim that based on our sample, there is a 95% chance that the true population mean of income (shown in red) lies within this range.</p>
<div class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>sns.swarmplot(data <span class="op">=</span> sample, y<span class="op">=</span><span class="st">'income'</span>,alpha<span class="op">=</span><span class="fl">0.5</span>) <span class="co"># plot a swarmplot of income</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>plt.axhline(df[<span class="st">'income'</span>].mean(), color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'solid'</span>, linewidth<span class="op">=</span><span class="dv">3</span>, label<span class="op">=</span><span class="st">'Population Mean'</span>) <span class="co"># add a horizontal line at the mean</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>plt.axhline(upper_ci, color<span class="op">=</span><span class="st">'black'</span>, linestyle<span class="op">=</span><span class="st">'dashed'</span>, linewidth<span class="op">=</span><span class="dv">3</span>) <span class="co"># add a dashed black line at the upper confidence interval</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>plt.axhline(lower_ci, color<span class="op">=</span><span class="st">'black'</span>, linestyle<span class="op">=</span><span class="st">'dashed'</span>, linewidth<span class="op">=</span><span class="dv">3</span>) <span class="co"># add a dashed black line at the lower confidence interval</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Income Distribution, 95% Confidence Interval'</span>) <span class="co"># add a title</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="30">
<pre><code>Text(0.5, 1.0, 'Income Distribution, 95% Confidence Interval')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="W07. Distributions and Basic Statistics_files/figure-html/cell-34-output-2.png" class="img-fluid"></p>
</div>
</div>
</section>
</section>
<section id="hypothesis-testing" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-testing">Hypothesis Testing</h2>
<p>If we create a boxplot of income disaggregated by sex using our sample, we can observe that men seem to earn more than women:</p>
<div class="cell" data-execution_count="31">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>sns.boxplot(data<span class="op">=</span>sample , x<span class="op">=</span><span class="st">'sex'</span>, y<span class="op">=</span><span class="st">'income'</span>).set_xticklabels([<span class="st">'Men'</span>,<span class="st">'Women'</span>]) <span class="co"># make a box plot of income by sex</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="31">
<pre><code>[Text(0, 0, 'Men'), Text(1, 0, 'Women')]</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="W07. Distributions and Basic Statistics_files/figure-html/cell-35-output-2.png" class="img-fluid"></p>
</div>
</div>
<p>But is this difference statistically significant? It could just be due to sampling error, random chance. <strong>Hypothesis testing</strong> provides a framework through which we can formally evaluate the likelihood of encountering an effect as extreme (in this case, the the difference between the mean incomes between both groups) as the one we observe in our data. There are four main steps in hypothesis testing:</p>
<ol type="1">
<li>State the hypotheses. H0 states that there is no difference between the two population means.</li>
<li>Select an <span class="math inline">\(\alpha\)</span> level (e.g.&nbsp;95% confidence), and select a corresponding <strong>critical value</strong> (1.96 for large samples)</li>
<li>Compute the test statistic.</li>
<li>Make a decision; if the test statistic exceeds the critical value, we <strong>reject the null hypothesis</strong>.</li>
</ol>
<p>Steps 1, 2, and 4 remain fairly constant regardless of what kind of hypothesis testing you’re conducting. Step 3 can vary quite a bit, as there are many different statistical tests that fall under the umbrella of hypothesis testing. In today’s workshop we’ll be using the Student’s T-Test (more on that in a second). For now, let’s begin the process of hypothesis testing a</p>
<section id="state-the-hypotheses" class="level3">
<h3 class="anchored" data-anchor-id="state-the-hypotheses">1. State the hypotheses</h3>
<section id="the-null-hypothesis" class="level4">
<h4 class="anchored" data-anchor-id="the-null-hypothesis">The Null Hypothesis</h4>
<ul>
<li><span class="math inline">\(H_0\)</span> : There is no difference in the mean income between men and women</li>
<li><span class="math inline">\(H_0\)</span> : <span class="math inline">\(\overline{x}_{men}&nbsp;=&nbsp;\overline{x}_{women}\)</span></li>
</ul>
</section>
<section id="the-alternative-hypothesis" class="level4">
<h4 class="anchored" data-anchor-id="the-alternative-hypothesis">The Alternative Hypothesis</h4>
<ul>
<li><span class="math inline">\(H_a\)</span> : There is a difference in the mean income between men and women</li>
<li><span class="math inline">\(H_a\)</span> : <span class="math inline">\(\overline{x}_{men}&nbsp;\neq&nbsp;\overline{x}_{women}\)</span></li>
</ul>
</section>
</section>
<section id="select-an-alpha-level" class="level3">
<h3 class="anchored" data-anchor-id="select-an-alpha-level">2. Select an <span class="math inline">\(\alpha\)</span> level</h3>
<p>Locate the critical region; the critical values for the t statistic are obtained using degrees of freedom (<span class="math inline">\(df=n-2\)</span>). Given that we have 1000 observations, <span class="math inline">\(df=998\)</span>. If <span class="math inline">\(df&gt;1000\)</span>, you can simply memorize the following critical values:</p>
<ul>
<li>At the 95% confidence level, the critical value is 1.96</li>
<li>At the 99% confidence level, the critical value is 2.58</li>
</ul>
<p>If our test statistic exceeds either of these values, we can reject the null hypothesis with the according level of confidence. The function below creates a plot which provides a visual reference for these values, but isn’t really necessary for the process of hypothesis testing. The function accepts one argument <code>test_statistic</code>, which it will use to plot a vertical red line. If the red line falls within the dotted lines, we fail to reject the null hypothesis at the corresponding confidence level. If it’s outside of these bounds, we reject the null hypothesis.</p>
<p>In the last line of code below, i’ve called the function to plot a test statistic of -2.3; Would we reject the null hypothesis at the 95% confidence level? what about the 99% level?</p>
<div class="cell" data-execution_count="32">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_z(test_statistic):</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>    mu, se<span class="op">=</span> <span class="dv">0</span>, <span class="dv">1</span> <span class="co"># create two variables, a mean "mu" equal to zero, and standard deviation "se" equal to 1</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> np.linspace(mu <span class="op">-</span> <span class="dv">3</span><span class="op">*</span>se, mu <span class="op">+</span> <span class="dv">3</span><span class="op">*</span>se, <span class="dv">100</span>) <span class="co"># create a range of values from -3 to 3 standard deviations</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>    plt.plot(x, norm.pdf(x, mu, se)) <span class="co"># plot the normal distribution</span></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>    plt.axvline(mu<span class="op">-</span>se<span class="op">*</span><span class="fl">1.96</span>, color<span class="op">=</span><span class="st">'blue'</span>, linestyle<span class="op">=</span><span class="st">'dashed'</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>,label<span class="op">=</span><span class="st">'µ ± 1.96σ (95</span><span class="sc">% c</span><span class="st">onfidence)'</span>) <span class="co"># plot a vertical line at the mean plus 2 standard deviations</span></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>    plt.axvline(mu<span class="op">+</span>se<span class="op">*</span><span class="fl">1.96</span>, color<span class="op">=</span><span class="st">'blue'</span>, linestyle<span class="op">=</span><span class="st">'dashed'</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>)  <span class="co"># plot a vertical line at the mean minus 2 standard deviations</span></span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>    plt.axvline(mu<span class="op">-</span>se<span class="op">*</span><span class="fl">2.58</span>, color<span class="op">=</span><span class="st">'green'</span>, linestyle<span class="op">=</span><span class="st">'dashed'</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>,label<span class="op">=</span><span class="st">'µ ± 2.58σ (99</span><span class="sc">% c</span><span class="st">onfidence)'</span>) <span class="co"># plot a vertical line at the mean plus 2 standard deviations</span></span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a>    plt.axvline(mu<span class="op">+</span>se<span class="op">*</span><span class="fl">2.58</span>, color<span class="op">=</span><span class="st">'green'</span>, linestyle<span class="op">=</span><span class="st">'dashed'</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>)  <span class="co"># plot a vertical line at the mean minus 2 standard deviations</span></span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a>    plt.axvline(test_statistic, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'solid'</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>,label<span class="op">=</span><span class="st">'Test Statistic'</span>) <span class="co"># plot a vertical line at the test statistic</span></span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-13"><a href="#cb51-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-14"><a href="#cb51-14" aria-hidden="true" tabindex="-1"></a>    plt.ylim(<span class="dv">0</span>,<span class="fl">0.4</span>)</span>
<span id="cb51-15"><a href="#cb51-15" aria-hidden="true" tabindex="-1"></a>    plt.legend()</span>
<span id="cb51-16"><a href="#cb51-16" aria-hidden="true" tabindex="-1"></a>    plt.title(<span class="st">'Z Distribution'</span>) <span class="co"># add a title</span></span>
<span id="cb51-17"><a href="#cb51-17" aria-hidden="true" tabindex="-1"></a>    plt.show()</span>
<span id="cb51-18"><a href="#cb51-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-19"><a href="#cb51-19" aria-hidden="true" tabindex="-1"></a>plot_z(<span class="op">-</span><span class="fl">2.3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="W07. Distributions and Basic Statistics_files/figure-html/cell-36-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="calculate-the-test-statistic-the-students-t-test" class="level3">
<h3 class="anchored" data-anchor-id="calculate-the-test-statistic-the-students-t-test">3. Calculate the Test Statistic (The Student’s T-Test)</h3>
<p>The Student’s T-Test is an <em>independent-measures design</em> which is used in situations where a researcher has no prior knowledge about either of the two populations (or treatments) being compared. In particular, the population means and standard deviations are all unknown. Because the population variances are not known, these values must be estimated from the sample data.</p>
<p>The purpose of a T-test is to determine whether the sample mean difference indicates a real mean difference between the two populations or whether the obtained difference is simply the result of sampling error. Given two groups, <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>, the <span class="math inline">\(t\)</span> statistic is calculated as:</p>
<p><span class="math display">\[ \Huge t = {\frac{\overline{x_1}-\overline{x_2}} {\sqrt{\frac{s^2_1}{n_1} + \frac{s^2_2}{n_2}}}} \]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(\overline{x}\)</span>: Sample Mean</li>
<li><span class="math inline">\(s^2\)</span>: Sample Standard Deviation</li>
<li><span class="math inline">\(n\)</span>: Number of observations</li>
</ul>
<p>We’ve already seen how to calculate each of these components when we made the 95% confidence interval above using the <code>.describe()</code> function. To calculate the t-statistic, we just have to plug these values into the formula above and do some basic arithmetic. I’ve put together a function that does this below, which accepts two main arguments, <code>group1</code> and <code>group2</code>. For each group it calculates descriptive statistics, and uses these values to calculate the t-statistic. It also has an optional argument <code>plot</code>, which when set to <code>True</code> will plot a 95% confidence interval for each group. It defaults to <code>False</code>, meaning that it won’t generate the plot.</p>
<div class="cell" data-execution_count="33">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> manual_ttest(group1, group2, plot<span class="op">=</span><span class="va">False</span>): <span class="co"># define a function called "manual_ttest" that takes two groups and a boolean value for whether or not to plot the results as arguments</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>    desc1, desc2<span class="op">=</span>group1.describe(), group2.describe() <span class="co"># get descriptive statistics for both samples</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>    n1,std1,mean1 <span class="op">=</span> desc1[<span class="st">'count'</span>], desc1[<span class="st">'std'</span>] ,desc1[<span class="st">'mean'</span>] <span class="co"># get the sample size, standard deviation, and mean of the first sample</span></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>    n2,std2,mean2 <span class="op">=</span> desc2[<span class="st">'count'</span>], desc2[<span class="st">'std'</span>] ,desc2[<span class="st">'mean'</span>] <span class="co"># get the sample size, standard deviation, and mean of the second sample</span></span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>    <span class="co"># calculate standard errors</span></span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>    se1, se2 <span class="op">=</span> std1<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n1, std2<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n2 <span class="co"># '**2' is the same as squaring the number</span></span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># standard error on the difference between the samples</span></span>
<span id="cb52-12"><a href="#cb52-12" aria-hidden="true" tabindex="-1"></a>    sed <span class="op">=</span> np.sqrt(se1 <span class="op">+</span> se2)</span>
<span id="cb52-13"><a href="#cb52-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-14"><a href="#cb52-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># calculate the t statistic</span></span>
<span id="cb52-15"><a href="#cb52-15" aria-hidden="true" tabindex="-1"></a>    t_stat <span class="op">=</span> (mean1 <span class="op">-</span> mean2) <span class="op">/</span> sed</span>
<span id="cb52-16"><a href="#cb52-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-17"><a href="#cb52-17" aria-hidden="true" tabindex="-1"></a>    <span class="co"># print the results</span></span>
<span id="cb52-18"><a href="#cb52-18" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Group 1: n=%.0f, mean=</span><span class="sc">%.3f</span><span class="st">, std=</span><span class="sc">%.3f</span><span class="st">"</span> <span class="op">%</span> (n1,mean1,std1)) </span>
<span id="cb52-19"><a href="#cb52-19" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Group 2: n=%.0f, mean=</span><span class="sc">%.3f</span><span class="st">, std=</span><span class="sc">%.3f</span><span class="st">"</span> <span class="op">%</span> (n2,mean2,std2))</span>
<span id="cb52-20"><a href="#cb52-20" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'The t-statistic is </span><span class="sc">%.3f</span><span class="st">'</span> <span class="op">%</span> t_stat) <span class="co"># print the t-statistic</span></span>
<span id="cb52-21"><a href="#cb52-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-22"><a href="#cb52-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> plot<span class="op">==</span><span class="va">True</span>: <span class="co"># if the plot argument is set to True, plot the results</span></span>
<span id="cb52-23"><a href="#cb52-23" aria-hidden="true" tabindex="-1"></a>        groups<span class="op">=</span>pd.DataFrame() <span class="co"># create an empty dataframe</span></span>
<span id="cb52-24"><a href="#cb52-24" aria-hidden="true" tabindex="-1"></a>        i<span class="op">=</span><span class="dv">1</span> <span class="co"># create a counter variable called "i" and set it equal to 1</span></span>
<span id="cb52-25"><a href="#cb52-25" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb52-26"><a href="#cb52-26" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> group <span class="kw">in</span> [group1, group2]: <span class="co"># loop through each group in the list of groups</span></span>
<span id="cb52-27"><a href="#cb52-27" aria-hidden="true" tabindex="-1"></a>            plot_df<span class="op">=</span>pd.DataFrame({<span class="st">'Values'</span>: group,<span class="st">'Group'</span>:i}) <span class="co"># create a dataframe with the values of the group and a column called "Group" that contains the group number</span></span>
<span id="cb52-28"><a href="#cb52-28" aria-hidden="true" tabindex="-1"></a>            groups<span class="op">=</span>groups.append(plot_df) <span class="co"># append the dataframe to the list of dataframes</span></span>
<span id="cb52-29"><a href="#cb52-29" aria-hidden="true" tabindex="-1"></a>            i<span class="op">+=</span><span class="dv">1</span> <span class="co"># increase the counter by 1</span></span>
<span id="cb52-30"><a href="#cb52-30" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb52-31"><a href="#cb52-31" aria-hidden="true" tabindex="-1"></a>        sns.pointplot(data<span class="op">=</span>groups , x<span class="op">=</span><span class="st">'Group'</span>, y<span class="op">=</span><span class="st">'Values'</span>,errorbar<span class="op">=</span>(<span class="st">'ci'</span>, <span class="dv">95</span>), color<span class="op">=</span><span class="st">'black'</span>, join<span class="op">=</span><span class="va">False</span>, capsize<span class="op">=</span><span class="fl">.8</span>) <span class="co"># plot the means of the groups with a 95% confidence interval</span></span>
<span id="cb52-32"><a href="#cb52-32" aria-hidden="true" tabindex="-1"></a>        plt.title(<span class="st">'Comparison of Group Means with 95% Confidence Intervals'</span>) <span class="co"># add a title</span></span>
<span id="cb52-33"><a href="#cb52-33" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb52-34"><a href="#cb52-34" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> t_stat <span class="co"># return the t-statistic</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Having defined the function, we can now call it to calculate a</p>
<div class="cell" data-execution_count="34">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>men<span class="op">=</span>sample[sample[<span class="st">'sex'</span>]<span class="op">==</span><span class="dv">1</span>] <span class="co"># filter the sample to only include men</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>women<span class="op">=</span>sample[sample[<span class="st">'sex'</span>]<span class="op">==</span><span class="dv">2</span>] <span class="co"># filter the sample to only include women</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>t <span class="op">=</span> manual_ttest(men[<span class="st">'income'</span>],women[<span class="st">'income'</span>]) <span class="co"># run the t-test function and store the t-statistic in a variable called "t"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Group 1: n=491, mean=55.719, std=35.562
Group 2: n=509, mean=38.320, std=27.705
The t-statistic is 8.610</code></pre>
</div>
</div>
</section>
<section id="make-a-decision" class="level3">
<h3 class="anchored" data-anchor-id="make-a-decision">4. Make a Decision</h3>
<p>If the t statistic indicates that the obtained difference between sample means (numerator) is substantially greater than the difference expected by chance (denominator), we reject H0 and conclude that there is a real mean difference between the two populations or treatments. Let plot the T-statistic from our test against the critical values:</p>
<div class="cell" data-execution_count="35">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>plot_z(t) <span class="co"># plot the test statistic on the z distribution</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="W07. Distributions and Basic Statistics_files/figure-html/cell-39-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Based on the plot above, can we reject the null hypothesis that there is no difference in mean income between men and women?</p>
</section>
<section id="exercise-6" class="level3">
<h3 class="anchored" data-anchor-id="exercise-6">Exercise</h3>
<ol type="1">
<li>From the main dataframe <code>df</code>, draw a sample of 500 white men. Using t-tests, investigate whether there are statistically significant discrepancies in pay between white men and other groups (note: it would be best to sample 500 people in each of those groups as well). Between what groups does there exist the most significant pay gap?</li>
<li>Some of this variation may be due to occupation. Compare income disparities between men and women within different occupations. Which occupation has the largest pay gap? which has the smallest?</li>
<li><a href="https://journals.sagepub.com/doi/abs/10.1177/0730888401028004005">Research suggests</a> that within occupational groups, collective bargaining through union membership reduces pay gaps. Read the abstract of this article, and try to replicate the analysis using our dataset.</li>
</ol>
<div class="cell" data-execution_count="36">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Statistics=8.610, p=0.000</code></pre>
</div>
</div>
</section>
</section>
<section id="extension-1" class="level2">
<h2 class="anchored" data-anchor-id="extension-1">Extension</h2>
<p>If this is all way too easy for you, here’s a different and less structured task. When Elon musk bought Twitter, he promisted to restore “free speech” to the platform. He heralded this new era with a tweet on 28/10/2022, which read “the bird is freed”. A tidal wave of hate speech ensued instead.</p>
<p>Using twitter’s API, I downloaded tweets containing a racial slur starting with N. Using the groupby function and regex, I counted the number of mentions of this word per hour on the platform for about a month before the takeover, and a few days thereafter. I’ve saved these counts (but not the tweets themselves) as a csv file called “elon_tweets.csv”.</p>
<p>The code below downloads this csv file, and plots the number of N-word containing tweets over time. Using a t-test and the full hypothesis testing procedure, investigate wheter there was a statistically significant increase in hate speech following Elon Musk’s tweet.</p>
<div class="cell" data-execution_count="44">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>curl https:<span class="op">//</span>storage.googleapis.com<span class="op">/</span>qm2<span class="op">/</span>wk7<span class="op">/</span>elon_twitter.csv <span class="op">-</span>o data<span class="op">/</span>wk7<span class="op">/</span>elon_twitter.csv</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4380  100  4380    0     0   8144      0 --:--:-- --:--:-- --:--:--  8217</code></pre>
</div>
</div>
<div class="cell" data-execution_count="47">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> datetime</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib.pyplot <span class="im">import</span> figure</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.dates <span class="im">as</span> mdates</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>tweets<span class="op">=</span>pd.read_csv(<span class="st">'data/wk7/elon_twitter.csv'</span>) <span class="co"># read in the data</span></span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">4</span>), dpi<span class="op">=</span><span class="dv">200</span>)</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>tweets[<span class="st">'hour'</span>]<span class="op">=</span>pd.to_datetime(tweets[<span class="st">'hour'</span>])</span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a>tweet<span class="op">=</span>datetime.datetime(<span class="dv">2022</span>, <span class="dv">10</span>, <span class="dv">28</span>)<span class="co">#.strftime('%d/%m/%Y %HH')</span></span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a>pre_mean<span class="op">=</span>tweets[tweets[<span class="st">'hour'</span>]<span class="op">&lt;</span>tweet][<span class="st">'count'</span>].mean()</span>
<span id="cb60-12"><a href="#cb60-12" aria-hidden="true" tabindex="-1"></a>post_mean<span class="op">=</span>tweets[tweets[<span class="st">'hour'</span>]<span class="op">&gt;</span>tweet][<span class="st">'count'</span>].mean()</span>
<span id="cb60-13"><a href="#cb60-13" aria-hidden="true" tabindex="-1"></a>pct_change<span class="op">=</span> <span class="bu">int</span>(((post_mean<span class="op">-</span>pre_mean)<span class="op">/</span>pre_mean)<span class="op">*</span><span class="dv">100</span>)</span>
<span id="cb60-14"><a href="#cb60-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-15"><a href="#cb60-15" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Hourly N-word Tweets'</span>)</span>
<span id="cb60-16"><a href="#cb60-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-17"><a href="#cb60-17" aria-hidden="true" tabindex="-1"></a>plt.plot_date(tweets[<span class="st">'hour'</span>], tweets[<span class="st">'count'</span>], <span class="st">'b-'</span>, color<span class="op">=</span><span class="st">'red'</span>)</span>
<span id="cb60-18"><a href="#cb60-18" aria-hidden="true" tabindex="-1"></a>plt.axvline(tweet, color<span class="op">=</span><span class="st">'black'</span>, linestyle<span class="op">=</span><span class="st">'dashed'</span>, label<span class="op">=</span><span class="st">'"the bird is freed"'</span>)</span>
<span id="cb60-19"><a href="#cb60-19" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb60-20"><a href="#cb60-20" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Elon Musk tweets "The bird is freed"; Tweets containing N-word increase </span><span class="sc">{}</span><span class="st">%'</span>.<span class="bu">format</span>(pct_change))</span>
<span id="cb60-21"><a href="#cb60-21" aria-hidden="true" tabindex="-1"></a>plt.gca().xaxis.set_major_locator(mdates.DayLocator())</span>
<span id="cb60-22"><a href="#cb60-22" aria-hidden="true" tabindex="-1"></a>plt.gca().xaxis.set_major_formatter(mdates.DateFormatter(<span class="st">'</span><span class="sc">%d</span><span class="st">/%m'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>/var/folders/6q/jt4x0r8n1rs0kbrrqrbj61fr0000gn/T/ipykernel_34310/354133693.py:17: UserWarning: color is redundantly defined by the 'color' keyword argument and the fmt string "b-" (-&gt; color='b'). The keyword argument will take precedence.
  plt.plot_date(tweets['hour'], tweets['count'], 'b-', color='red')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="W07. Distributions and Basic Statistics_files/figure-html/cell-42-output-2.png" class="img-fluid"></p>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../Week 6.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Group Presentations</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../Week 8.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>