<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.326">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Quantitative Methods 2 - Regression Discontinuity</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../notebooks/W08. Diff-in-Diff.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script type="text/javascript">

(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
ga('create', 'UA-154866877-2', 'auto');

ga('send', {
  hitType: 'pageview',
  'anonymizeIp': true,
});
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>
<script src="https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js" crossorigin="anonymous"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../notebooks/W09. Regression Discontinuity.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Regression Discontinuity</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="../logo2.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Quantitative Methods 2</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/oballinger/QM2/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Download" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Download"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="../Quantitative-Methods-2.pdf">
              <i class="bi bi-bi-file-pdf pe-1"></i>
            Download PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="../Quantitative-Methods-2.epub">
              <i class="bi bi-bi-journal pe-1"></i>
            Download ePub
            </a>
          </li>
      </ul>
    </div>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-1" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-1">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/W01. Python Recap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Python Recap</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/W02. Pandas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Intro to Pandas</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/W03. Spatial Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Spatiotemporal Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/W04. Natural Language Processing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Natural Language Processing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/W05. Distributions and Basic Statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Distributions and Basic Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/RW. Merging and Joining.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Merging and Joining</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/W06. Hypothesis Testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/W07. Linear Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/W08. Diff-in-Diff.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Difference in Differences</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/W09. Regression Discontinuity.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Regression Discontinuity</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#workshop-09-open-in-colab" id="toc-workshop-09-open-in-colab" class="nav-link active" data-scroll-target="#workshop-09-open-in-colab"><em>Workshop 09</em> <img src="https://github.com/oballinger/QM2/blob/main/colab-badge.png?raw=1" class="img-fluid" alt="Open In Colab"></a></li>
  <li><a href="#spatial-discontinuities" id="toc-spatial-discontinuities" class="nav-link" data-scroll-target="#spatial-discontinuities">Spatial Discontinuities</a>
  <ul class="collapse">
  <li><a href="#is-alcohol-killing-you" id="toc-is-alcohol-killing-you" class="nav-link" data-scroll-target="#is-alcohol-killing-you">Is Alcohol Killing You?</a></li>
  <li><a href="#rdd-estimation" id="toc-rdd-estimation" class="nav-link" data-scroll-target="#rdd-estimation">RDD Estimation</a></li>
  </ul></li>
  <li><a href="#assessed-question" id="toc-assessed-question" class="nav-link" data-scroll-target="#assessed-question">Assessed Question</a>
  <ul class="collapse">
  <li><a href="#kernel-weighting" id="toc-kernel-weighting" class="nav-link" data-scroll-target="#kernel-weighting">Kernel Weighting</a></li>
  <li><a href="#sheepskin-effect-and-fuzzy-rdd" id="toc-sheepskin-effect-and-fuzzy-rdd" class="nav-link" data-scroll-target="#sheepskin-effect-and-fuzzy-rdd">Sheepskin Effect and Fuzzy RDD</a>
  <ul class="collapse">
  <li><a href="#the-mccrary-test" id="toc-the-mccrary-test" class="nav-link" data-scroll-target="#the-mccrary-test">The McCrary Test</a></li>
  </ul></li>
  <li><a href="#key-ideas" id="toc-key-ideas" class="nav-link" data-scroll-target="#key-ideas">Key Ideas</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  <li><a href="#contribute" id="toc-contribute" class="nav-link" data-scroll-target="#contribute">Contribute</a></li>
  </ul></li>
  <li><a href="#assessed-question-1" id="toc-assessed-question-1" class="nav-link" data-scroll-target="#assessed-question-1">Assessed Question</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.dev/oballinger/QM2/blob/main/notebooks/W09. Regression Discontinuity.ipynb" class="toc-action">Edit this page</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Regression Discontinuity</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="workshop-09-open-in-colab" class="level2">
<h2 class="anchored" data-anchor-id="workshop-09-open-in-colab"><em>Workshop 09</em> <a href="https://colab.research.google.com/github/oballinger/QM2/blob/main/notebooks/W09.%20Regression%20Discontinuity.ipynb"><img src="https://github.com/oballinger/QM2/blob/main/colab-badge.png?raw=1" class="img-fluid" alt="Open In Colab"></a></h2>
<p>In this final week, we’re going to look at Regression Discontinuity Designs (RDD). We’ll look into discontinuities in two types of variables:</p>
<ol type="1">
<li>Spatial discontinuities</li>
<li>Temporal discontinuities</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>mkdir data</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>curl https:<span class="op">//</span>storage.googleapis.com<span class="op">/</span>qm2<span class="op">/</span>wk10<span class="op">/</span>geojson<span class="op">-</span>counties<span class="op">-</span>fips.json <span class="op">-</span>o data<span class="op">/</span>geojson<span class="op">-</span>counties<span class="op">-</span>fips.json</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>mkdir: data: File exists
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3141k  100 3141k    0     0  28.2M      0 --:--:-- --:--:-- --:--:-- 30.0M
&lt;?xml version='1.0' encoding='UTF-8'?&gt;&lt;Error&gt;&lt;Code&gt;NoSuchKey&lt;/Code&gt;&lt;Message&gt;The specified key does not exist.&lt;/Message&gt;&lt;Details&gt;No such object: qm2/wk10/county_labor.csv-o&lt;/Details&gt;&lt;/Error&gt;curl: (6) Could not resolve host: data
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9177  100  9177    0     0   260k      0 --:--:-- --:--:-- --:--:--     0- --:--:-- --:--:--  298k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1728  100  1728    0     0  70895      0 --:--:-- --:--:-- --:--:-- 82285</code></pre>
</div>
</div>
<div class="cell" data-tags="[&quot;hide-input&quot;]" data-execution_count="2">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">'ignore'</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib <span class="im">import</span> style</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib <span class="im">import</span> pyplot <span class="im">as</span> plt</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> geopandas <span class="im">as</span> gpd</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.formula.api <span class="im">import</span> ols</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>matplotlib inline</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>style.use(<span class="st">"fivethirtyeight"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="spatial-discontinuities" class="level1">
<h1>Spatial Discontinuities</h1>
<p>Last week, we set up a difference model and made causal claims about the effect of minimum wage laws on unemployment. We did this by treating Pennsylvania as a control group for New Jersey on the basis that they had similar trends in unemployment before the minimum wage law, and diverging trends after, and no other shock coincided with this policy.</p>
<p>We could still poke some holes in that– NJ seems to have fared worse than PA after the 2008 crisis; maybe more people work in finance in NJ. Indeed, Jersey City is across the water from Manhattan, America’s financial centre. Bankers would be hard hit by a financial crisis, but are probably not that affected by minimum wage laws. Conversely, Pennsylvania is the 3rd largest coal-producing state in the U.S.– coal miners are probably less affected by financial crises, but more likely to be earning minimum wage. As such, increasing the minimum wage in a place where most people are bankers probably has less of an effect on unemployment compared to an area where everyone is a coal miner.</p>
<p>Running a state-level analysis is subject to this sort of selection bias, since by looking at state averages we’re effectively comparing places like Jersey City to places like <a href="https://en.wikipedia.org/wiki/Centralia,_Pennsylvania">Centralia</a>, a coal-mining town in central Pennsylvania which saw its population decline from 1000 in 1980 to just five residents in 2020. So the next step in our analysis might be to try to compare apples to apples. There are a number of ways of doing this– we could look at the unemployment rate by industry, for example. But what if we didn’t want to rely on pre-trends, or if we didn’t even have data prior to the treatment? This is often the case</p>
<p>To build a more valid counterfactual, we can drill even deeper to find even more similar comparison groups using a <strong>Regression Discontinuity Design (RDD)</strong> using county (rather than state) level data.</p>
<blockquote class="blockquote">
<p><strong><a href="https://www.princeton.edu/~davidlee/wp/RDDEconomics.pdf">Regression Discontinuity Designs</a></strong> are a method of estimating treatment effects in a nonexperimental setting where treatment is determined by whether an observed “assignment” variable exceeds a known cutoff point. If the cutoff is exogenous to the treatment, observations in the vicinity of this cutoff are likely to be very similar, and assignment to the treatment or control group can be considered as good as random.</p>
</blockquote>
<p>RDD models generally take the following form:</p>
<p><span class="math display">\[\huge Y_{i} = \beta_0 + \beta_1 R_i + \beta_2 T_i + \varepsilon_{i}\]</span></p>
<p><span class="math display">\[\large T_i=    \begin{cases}
      1 &amp; R_i&gt;c\\
      0 &amp; R_i&lt;c\\
    \end{cases} \]</span></p>
<p>Where R is the “running variable”, T is the treatment variable, and c is a cutoff in the running variable assigning observations to the “treatment” or “control” groups.</p>
<p>In our case, the treatment is the minimum wage law passed in NJ in 2014. We want to be looking at the period after this to pick up on any changes in employment. The <strong>assignment variable</strong> in this case could be the distance of a county to the border between the two states, and the sharp cutoff would be the border itself. Counties on the border counties are probably much more similar to each other than other, farther away counties: this would exclude both Jersey City (in the far east of NJ) and Centralia (in the centre of PA).</p>
<p>Indeed, several cities are divided by the border between these states including Philladelphia, the capital city of Pennsylvania:</p>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> ipyleaflet <span class="im">import</span> Map, Marker, basemaps, basemap_to_tiles</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>Map(basemap<span class="op">=</span>basemap_to_tiles(</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    basemaps.Esri.WorldImagery),</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  center<span class="op">=</span>(<span class="fl">39.95279958991338</span>, <span class="op">-</span><span class="fl">75.1341365382268</span>),</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  zoom<span class="op">=</span><span class="dv">14</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<script type="application/vnd.jupyter.widget-view+json">
{"model_id":"02537c2f86bf439ca5b36b31c53f2bb8","version_major":2,"version_minor":0,"quarto_mimetype":"application/vnd.jupyter.widget-view+json"}
</script>
</div>
</div>
<p>On the left side of the river is Philladelphia, PA, while on the right side is Camden, NJ. The code below uses the county shapefile we used before to isolate the counties in NJ and PA that are on the border.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>counties<span class="op">=</span>pd.read_csv(<span class="st">'https://storage.googleapis.com/qm2/wk10/county_labor.csv'</span>, dtype<span class="op">=</span>{<span class="st">'county_fips'</span>:<span class="bu">str</span>}) <span class="co"># read in the county labor data</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>shp <span class="op">=</span> gpd.read_file(<span class="st">'data/geojson-counties-fips.json'</span>) <span class="co"># read in the counties shapefile</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>subset<span class="op">=</span>shp[shp[<span class="st">'STATE'</span>].isin([<span class="st">'34'</span>,<span class="st">'42'</span>])] <span class="co"># new jersey = 34, pennsylvania = 42, new york = 36</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>subset[<span class="st">'neighbors'</span>]<span class="op">=</span> <span class="dv">0</span> <span class="co"># create a new column called neighbors</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> index, row <span class="kw">in</span> subset.iterrows():  <span class="co"># iterate through each row in the counties shapefile</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    buffered<span class="op">=</span> row[<span class="st">'geometry'</span>].<span class="bu">buffer</span>(<span class="fl">0.1</span>) <span class="co"># create a buffer around the county so that it overlaps with its neighbors</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    neighbors <span class="op">=</span> <span class="bu">list</span>(<span class="bu">set</span>(subset[subset.geometry.overlaps(buffered)].STATE.tolist()).difference([row.STATE])) <span class="co"># check which counties overlap with the buffer, grab the state code, and remove the current county's state code</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    subset.at[index, <span class="st">"neighbors"</span>] <span class="op">=</span> <span class="st">", "</span>.join(neighbors) <span class="co"># add the list of neighbors to the neighbors column</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>subset[<span class="st">'border'</span>]<span class="op">=</span>np.where(subset[<span class="st">'neighbors'</span>]<span class="op">==</span><span class="st">''</span>,<span class="dv">0</span>,<span class="dv">1</span>) <span class="co"># create a new column called border that is 1 if the county is on the border and 0 if it is not</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>subset[<span class="st">'viscol'</span>]<span class="op">=</span>subset[<span class="st">'STATE'</span>].astype(<span class="bu">int</span>)<span class="op">+</span>subset[<span class="st">'border'</span>] <span class="co"># create a new column that combines the state code and the border column</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>subset.plot(column<span class="op">=</span><span class="st">'viscol'</span>,legend<span class="op">=</span><span class="va">False</span>, figsize<span class="op">=</span>(<span class="dv">20</span>,<span class="dv">10</span>), cmap<span class="op">=</span><span class="st">'RdYlGn'</span>) <span class="co"># plot the counties and color them by the border column</span></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Border Counties in New Jersey and Pennsylvania'</span>, fontsize<span class="op">=</span><span class="dv">20</span>) <span class="co"># add a title</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="23">
<pre><code>Text(0.5, 1.0, 'Border Counties in New Jersey and Pennsylvania')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="W09. Regression Discontinuity_files/figure-html/cell-5-output-2.png" class="img-fluid"></p>
</div>
</div>
<p>We can now restrict our sample to only include counties within a set distance the border, and set up a regression discontinuity design in which:</p>
<ul>
<li>unemployment is the dependent variable.</li>
<li>state (NJ/PA) is the treatment variable.</li>
<li>distance from the border is the running variable.</li>
</ul>
<div class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>border_counties<span class="op">=</span>subset[subset[<span class="st">'border'</span>]<span class="op">==</span><span class="dv">1</span>][<span class="st">'id'</span>].tolist() <span class="co"># create a list of the border counties</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>rdd<span class="op">=</span>counties[(counties[<span class="st">'year'</span>]<span class="op">&gt;</span><span class="dv">2007</span>)<span class="op">&amp;</span>(counties[<span class="st">'county_fips'</span>].isin(border_counties))] <span class="co"># subset the counties data to only include border counties and years after 2007</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>rdd_model <span class="op">=</span> ols(<span class="st">'unemployment ~ C(state)'</span>, rdd[rdd[<span class="st">'year'</span>]<span class="op">&gt;</span><span class="dv">2014</span>]).fit()</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(rdd_model.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:           unemployment   R-squared:                       0.032
Model:                            OLS   Adj. R-squared:                  0.023
Method:                 Least Squares   F-statistic:                     3.394
Date:                Fri, 01 Dec 2023   Prob (F-statistic):             0.0683
Time:                        12:53:28   Log-Likelihood:                -211.58
No. Observations:                 105   AIC:                             427.2
Df Residuals:                     103   BIC:                             432.5
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==================================================================================
                     coef    std err          t      P&gt;|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept          5.2518      0.245     21.446      0.000       4.766       5.737
C(state)[T.42]     0.6605      0.358      1.842      0.068      -0.051       1.371
==============================================================================
Omnibus:                       21.953   Durbin-Watson:                   0.637
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               27.712
Skew:                           1.141   Prob(JB):                     9.60e-07
Kurtosis:                       4.061   Cond. No.                         2.55
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p>This gives us a much better idea of the impact of the minimum wage law by discarding counties that are very far away from eachother and thus dissimilar. We can see that border counties in Pennsylvania saw a 0.66% <em>increase</em> in unemployment relative to border counties in New Jersey, in the years following the latter’s implementation of the minimum wage increase. This difference, however, is not statistically significant.</p>
<p>This example captures the basic intuition behind regression discontinuity, but we might worry that the minimum wage law isn’t the only thing that changes as the discontinutiy (i.e., isn’t the only thing that changes between NJ and PA).</p>
<p>It is quite common to use distance as a running variable in RDD, and if you’re interested in a review of the literature on spatial RDD models check out <a href="https://www.jstor.org/stable/24572845">this article</a>.</p>
<p>To get a firm grasp of the intuition and mechanics behind RDD, we’ll use a more straightforward example.</p>
<section id="is-alcohol-killing-you" class="level2">
<h2 class="anchored" data-anchor-id="is-alcohol-killing-you">Is Alcohol Killing You?</h2>
<p>A very relevant public policy question is what should be the minimal drinking age. Most countries, Brazil included, set it to be 18 year, but in the US (most states) it is currently 21. So, is it the case that the US is being overly prudent and that they should lower their minimal drinking age? Or is it the case that other countries should make their legal drinking age higher?</p>
<p>One way to look at this question is from a <a href="https://www.aeaweb.org/articles?id=10.1257/app.1.1.164">mortality rate perspective (Carpenter and Dobkin, 2009)</a>. From the public policy standpoint, one could argue that we should lower the mortality rate as much as possible. If alcohol consumption increases the mortality rate by a lot, we should avoid lowering the minimum drinking age. This would be consistent with the objective of lowering deaths caused by alcohol consumption.</p>
<p>To estimate the impacts of alcohol on death, we could use the fact that legal drinking age imposes a discontinuity on nature. In the US, those just under 21 years don’t drink (or drink much less) while those just older than 21 do drink. This means that the probability of drinking jumps at 21 years and that is something we can explore with an RDD.</p>
<p>To do so we can grab some mortality data aggregated by age. Each row is the average age of a group of people and the average mortality by all causes (<code>all</code>), by moving vehicle accident (<code>mva</code>) and by suicide (<code>suicide</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>drinking <span class="op">=</span> pd.read_csv(<span class="st">"https://storage.googleapis.com/qm2/rdd/drinking.csv"</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>drinking.head()[[<span class="st">"agecell"</span>, <span class="st">"all"</span>, <span class="st">"mva"</span>, <span class="st">"suicide"</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="31">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">agecell</th>
<th data-quarto-table-cell-role="th">all</th>
<th data-quarto-table-cell-role="th">mva</th>
<th data-quarto-table-cell-role="th">suicide</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>19.068493</td>
<td>92.825400</td>
<td>35.829327</td>
<td>11.203714</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>19.150684</td>
<td>95.100740</td>
<td>35.639256</td>
<td>12.193368</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>19.232876</td>
<td>92.144295</td>
<td>34.205650</td>
<td>11.715812</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>19.315070</td>
<td>88.427760</td>
<td>32.278957</td>
<td>11.275010</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>19.397260</td>
<td>88.704940</td>
<td>32.650967</td>
<td>10.984314</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Just to aid visibility (and for another important reason we will see later) we will centralize the running variable <code>agecell</code> at the threshold 21.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>drinking[<span class="st">"agecell"</span>] <span class="op">-=</span> <span class="dv">21</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If we plot the multiple outcome variables (<code>all</code>, <code>mva</code>, <code>suicide</code>) with the runing variable on the x axis, we get some visual cue about some sort of jump in mortality as we cross the legal drinking age.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>,<span class="dv">8</span>))</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> plt.subplot(<span class="dv">3</span>,<span class="dv">1</span>,<span class="dv">1</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>drinking.plot.scatter(x<span class="op">=</span><span class="st">"agecell"</span>, y<span class="op">=</span><span class="st">"all"</span>, ax<span class="op">=</span>ax)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Death Cause by Age (Centered at 0)"</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> plt.subplot(<span class="dv">3</span>,<span class="dv">1</span>,<span class="dv">2</span>, sharex<span class="op">=</span>ax)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>drinking.plot.scatter(x<span class="op">=</span><span class="st">"agecell"</span>, y<span class="op">=</span><span class="st">"mva"</span>, ax<span class="op">=</span>ax)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> plt.subplot(<span class="dv">3</span>,<span class="dv">1</span>,<span class="dv">3</span>, sharex<span class="op">=</span>ax)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>drinking.plot.scatter(x<span class="op">=</span><span class="st">"agecell"</span>, y<span class="op">=</span><span class="st">"suicide"</span>, ax<span class="op">=</span>ax)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="W09. Regression Discontinuity_files/figure-html/cell-9-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>There are some cues, but we need more than that. What exactly is the effect of drinking on mortality at the threshold? And what is the standard error on that estimate?</p>
</section>
<section id="rdd-estimation" class="level2">
<h2 class="anchored" data-anchor-id="rdd-estimation">RDD Estimation</h2>
<p>The key assumption that RDD relies on is the smoothness of the potential outcome at the threshold. We can think of RDD as a local randomized trial. For those at the threshold, the treatment could have gone either way and, by chance, some people fell below the threshold, and some people fell above. In our example, at the same point in time, some people are just above 21 years and some people are just below 21. What determines this is if someone was born some days later or not, which is pretty random. For this reason, RDD provides a very compelling causal story. It is not the golden standard of RCT, but it is close.</p>
<p>Now, to estimate the treatment effect at the threshold, all we need to do is estimate both of the limits in the formula above and compare them. The simplest way to do that is by running a linear regression</p>
<p>To make it work, we interact a dummy for being above the threshold with the running variable</p>
<p>$ y_i = _0 + _1 r_i + _2 {r_i&gt;c} + _3 {r_i&gt;c} r_i $</p>
<p>Essentially, this is the same as fitting a linear regression above the threshold and another below it. The parameter <span class="math inline">\(\beta_0\)</span> is the intercept of the regression below the threshold and <span class="math inline">\(\beta_0+\beta_2\)</span> is the intercept for the regression above the threshold.</p>
<p>Here is where the trick of centering the running variable at the threshold comes into play. After this pre-processing step, the threshold becomes zero. This causes the intercept <span class="math inline">\(\beta_0\)</span> to be the predicted value at the threshold, for the regression below it. By the same reasoning, <span class="math inline">\(\beta_0+\beta_2\)</span> is the limit of the outcome from above.</p>
<p>Here is what this looks like in code for the case where we want to estimate the effect of alcohol consumption on death by all causes at 21 years.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>rdd_df <span class="op">=</span> drinking.assign(threshold<span class="op">=</span>(drinking[<span class="st">"agecell"</span>] <span class="op">&gt;</span> <span class="dv">0</span>).astype(<span class="bu">int</span>))</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> smf.wls(<span class="st">"all~ agecell * threshold "</span>, rdd_df).fit()</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            WLS Regression Results                            
==============================================================================
Dep. Variable:                    all   R-squared:                       0.668
Model:                            WLS   Adj. R-squared:                  0.645
Method:                 Least Squares   F-statistic:                     29.47
Date:                Fri, 10 Mar 2023   Prob (F-statistic):           1.33e-10
Time:                        11:18:58   Log-Likelihood:                -105.64
No. Observations:                  48   AIC:                             219.3
Df Residuals:                      44   BIC:                             226.8
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
=====================================================================================
                        coef    std err          t      P&gt;|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept            93.6184      0.932    100.399      0.000      91.739      95.498
agecell               0.8270      0.819      1.010      0.318      -0.823       2.477
threshold             7.6627      1.319      5.811      0.000       5.005      10.320
agecell:threshold    -3.6034      1.158     -3.111      0.003      -5.937      -1.269
==============================================================================
Omnibus:                        0.294   Durbin-Watson:                   1.965
Prob(Omnibus):                  0.863   Jarque-Bera (JB):                0.411
Skew:                           0.167   Prob(JB):                        0.814
Kurtosis:                       2.693   Cond. No.                         7.75
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p>This model is telling us that mortality increases by 7.6627 points with the consumption of alcohol. Another way of putting this is that alcohol increases the chance of death by all causes by 8% <span class="math inline">\((100*((7.6627+93.6184)/93.6184 - 1))\)</span>. Notice that this also gives us standard errors for our causal effect estimate. In this case, the effect is statistically significant, since the p-value is below 0.01. We can calculate the treatment effect programattically as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>ate_pct <span class="op">=</span> <span class="dv">100</span><span class="op">*</span>((model.params[<span class="st">"threshold"</span>] <span class="op">+</span> model.params[<span class="st">"Intercept"</span>])<span class="op">/</span>model.params[<span class="st">"Intercept"</span>] <span class="op">-</span> <span class="dv">1</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Alcohol increases the chance of death by all causes by </span><span class="sc">{}</span><span class="st">%"</span>.<span class="bu">format</span>(np.<span class="bu">round</span>(ate_pct,<span class="dv">2</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Alcohol increases the chance of death by all causes by 8.19%</code></pre>
</div>
</div>
<p>If we want to verify this model visually, we can show the predicted values on the data that we have. You can see that it is as though we had 2 regression models: one for those above the threshold and one for below it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> drinking.plot.scatter(x<span class="op">=</span><span class="st">"agecell"</span>, y<span class="op">=</span><span class="st">"all"</span>, color<span class="op">=</span><span class="st">"C0"</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>drinking.assign(predictions<span class="op">=</span>model.fittedvalues).plot(x<span class="op">=</span><span class="st">"agecell"</span>, y<span class="op">=</span><span class="st">"predictions"</span>, ax<span class="op">=</span>ax, color<span class="op">=</span><span class="st">"C1"</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="ss">f"Impact of Alcohol on Death: </span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">round</span>(ate_pct, <span class="dv">2</span>)<span class="sc">}</span><span class="ss">% </span><span class="ch">\n</span><span class="ss"> p=</span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">round</span>(model.pvalues[<span class="st">'threshold'</span>], <span class="dv">3</span>)<span class="sc">}</span><span class="ss">, R2=</span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">round</span>(model.rsquared, <span class="dv">3</span>)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="W09. Regression Discontinuity_files/figure-html/cell-12-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
</section>
<section id="assessed-question" class="level1">
<h1>Assessed Question</h1>
<p>You’ll remember from the lecture slides that the model we’ve fit above is a linear, different slopes design. Try fitting the following models:</p>
<ol type="1">
<li>Linear, Same Slopes</li>
<li>Linear, Different Slopes</li>
</ol>
<p>Pay attention to the treatment effect. Is it consistent across models? Which model has the highest treatment effect? Which model fits the best?</p>
<section id="kernel-weighting" class="level3">
<h3 class="anchored" data-anchor-id="kernel-weighting">Kernel Weighting</h3>
<p>Regression Discontinuity relies heavily on the extrapolations properties of linear regression. Since we are looking at the values at the beginning and end of 2 regression lines, we better get those limits right. What can happen is that regression might focus too much on fitting the other data points at the cost of a poor fit at the threshold. If this happens, we might get the wrong measure of the treatment effect.</p>
<p>One way to solve this is to give higher weights for the points that are closer to the threshold. There are many ways to do this, but a popular one is to reweight the samples with the <strong>triangular kernel</strong></p>
<p>$ K(R, c, h) = {|R-c| h} * (1-) $</p>
<p>The first part of this kernel is an indicator function to whether we are close to the threshold. How close? This is determined by a bandwidth parameter <span class="math inline">\(h\)</span>. The second part of this kernel is a weighting function. As we move away from the threshold, the weights get smaller and smaller. These weights are divided by the bandwidth. If the bandwidth is large, the weights get smaller at a slower rate. If the bandwidth is small, the weights quickly go to zero.</p>
<p>To make it easier to understand, here is what the weights look like for this kernel applied to our problem. I’ve set the bandwidth to be 1 here, meaning we will only consider data from people that are no older than 22 years and no younger than 20 years.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> kernel(R, c, h):</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    indicator <span class="op">=</span> (np.<span class="bu">abs</span>(R<span class="op">-</span>c) <span class="op">&lt;=</span> h).astype(<span class="bu">float</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> indicator <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> np.<span class="bu">abs</span>(R<span class="op">-</span>c)<span class="op">/</span>h)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>plt.plot(drinking[<span class="st">"agecell"</span>], kernel(drinking[<span class="st">"agecell"</span>], c<span class="op">=</span><span class="dv">0</span>, h<span class="op">=</span><span class="dv">1</span>))</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"agecell"</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Weight"</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Kernel Weight by Age"</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="W09. Regression Discontinuity_files/figure-html/cell-15-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>If we apply these weights to our original problem, the impact of alcohol gets bigger, at least for all causes. It jumps from 7.6627 to 9.7004. The result remains very significant. Also, notice that I’m using <code>wls</code> instead of <code>ols</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> smf.wls(<span class="st">"all~agecell*threshold"</span>, rdd_df,</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>                weights<span class="op">=</span>kernel(drinking[<span class="st">"agecell"</span>], c<span class="op">=</span><span class="dv">0</span>, h<span class="op">=</span><span class="dv">1</span>)).fit()</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>model.summary().tables[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="20">
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td></td>
<td data-quarto-table-cell-role="th">coef</td>
<td data-quarto-table-cell-role="th">std err</td>
<td data-quarto-table-cell-role="th">t</td>
<td data-quarto-table-cell-role="th">P&gt;|t|</td>
<td data-quarto-table-cell-role="th">[0.025</td>
<td data-quarto-table-cell-role="th">0.975]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Intercept</td>
<td>93.2002</td>
<td>0.731</td>
<td>127.429</td>
<td>0.000</td>
<td>91.726</td>
<td>94.674</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">agecell</td>
<td>0.4109</td>
<td>1.789</td>
<td>0.230</td>
<td>0.819</td>
<td>-3.196</td>
<td>4.017</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">threshold</td>
<td>9.7004</td>
<td>1.034</td>
<td>9.378</td>
<td>0.000</td>
<td>7.616</td>
<td>11.785</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">agecell:threshold</td>
<td>-7.1759</td>
<td>2.531</td>
<td>-2.835</td>
<td>0.007</td>
<td>-12.276</td>
<td>-2.075</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> drinking.plot.scatter(x<span class="op">=</span><span class="st">"agecell"</span>, y<span class="op">=</span><span class="st">"all"</span>, color<span class="op">=</span><span class="st">"C0"</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>drinking.assign(predictions<span class="op">=</span>model.fittedvalues).plot(x<span class="op">=</span><span class="st">"agecell"</span>, y<span class="op">=</span><span class="st">"predictions"</span>, ax<span class="op">=</span>ax, color<span class="op">=</span><span class="st">"C1"</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Regression Discontinuity (Local Regression)"</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="W09. Regression Discontinuity_files/figure-html/cell-17-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>And here is what it looks like for the other causes of death. Notice how the regression on the right is more negatively sloped since it disconsiders the right most points.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>,<span class="dv">8</span>))</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>weights <span class="op">=</span> kernel(drinking[<span class="st">"agecell"</span>], c<span class="op">=</span><span class="dv">0</span>, h<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> p, cause <span class="kw">in</span> <span class="bu">enumerate</span>([<span class="st">"all"</span>, <span class="st">"mva"</span>, <span class="st">"suicide"</span>], <span class="dv">1</span>):</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    ax <span class="op">=</span> plt.subplot(<span class="dv">3</span>,<span class="dv">1</span>,p)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    drinking.plot.scatter(x<span class="op">=</span><span class="st">"agecell"</span>, y<span class="op">=</span>cause, ax<span class="op">=</span>ax)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>    m <span class="op">=</span> smf.wls(<span class="ss">f"</span><span class="sc">{</span>cause<span class="sc">}</span><span class="ss">~agecell*threshold"</span>, rdd_df, weights<span class="op">=</span>weights).fit()</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>    ate_pct <span class="op">=</span> <span class="dv">100</span><span class="op">*</span>((m.params[<span class="st">"threshold"</span>] <span class="op">+</span> m.params[<span class="st">"Intercept"</span>])<span class="op">/</span>m.params[<span class="st">"Intercept"</span>] <span class="op">-</span> <span class="dv">1</span>)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>    drinking.assign(predictions<span class="op">=</span>m.fittedvalues).plot(x<span class="op">=</span><span class="st">"agecell"</span>, y<span class="op">=</span><span class="st">"predictions"</span>, ax<span class="op">=</span>ax, color<span class="op">=</span><span class="st">"C1"</span>)</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>    plt.title(<span class="ss">f"Impact of Alcohol on Death: </span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">round</span>(ate_pct, <span class="dv">2</span>)<span class="sc">}</span><span class="ss">%"</span>)</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="W09. Regression Discontinuity_files/figure-html/cell-18-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>With the exception of suicide, it looks like adding the kernel weight made the negative impact on alcohol bigger. Once again, if we want to minimize the death rate, we should NOT recommend lowering the legal drinking age, since there is a clear impact of alcohol on the death rates.</p>
<p>This simple case covers what happens when regression discontinuity design works perfectly. Next, we will see some diagnostics that we should run in order to check how much we can trust RDD and talk about a topic that is very dear to our heart: the effect of education on earnings.</p>
</section>
<section id="sheepskin-effect-and-fuzzy-rdd" class="level2">
<h2 class="anchored" data-anchor-id="sheepskin-effect-and-fuzzy-rdd">Sheepskin Effect and Fuzzy RDD</h2>
<p>When it comes to the effect of education on earnings, there are two major views in economics. The first one is the widely known argument that education increases human capital, increasing productivity and thus, earnings. In this view, education actually changes you for the better. Another view is that education is simply a signaling mechanism. It just puts you through all these hard tests and academic tasks. If you can make it, it signals to the market that you are a good employee. In this way, education doesn’t make you more productive. It only tells the market how productive you have always been. What matters here is the diploma. If you have it, you will be paid more. We refer to this as the <strong>sheepskin effect</strong>, since diplomas were printed in sheepskin in the past.</p>
<p>To test this hypothesis, <a href="https://faculty.smu.edu/millimet/classes/eco7321/papers/clark%20martorell%202014.pdf">Clark and Martorell</a> used regression discontinuity to measure the effect of graduating 12th grade on earnings. In order to do that, they had to think about some running variable where students that fall above it graduate and those who fall below it, don’t. They found such data in the Texas education system.</p>
<p>In order to graduate in Texas, one has to pass an exam. Testing starts at 10th grade and students can do it multiple times, but eventually, they face a last chance exam at the end of 12th grade. The idea was to get data from students who took those last chance exams and compare those that had barely failed it to those that barely passed it. These students will have very similar human capital, but different signaling credentials. Namely, those that barely passed it, will receive a diploma.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>sheepskin <span class="op">=</span> pd.read_csv(<span class="st">"https://storage.googleapis.com/qm2/rdd/sheepskin.csv"</span>)[[<span class="st">"avgearnings"</span>, <span class="st">"minscore"</span>, <span class="st">"receivehsd"</span>, <span class="st">"n"</span>]]</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>sheepskin.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="23">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">avgearnings</th>
<th data-quarto-table-cell-role="th">minscore</th>
<th data-quarto-table-cell-role="th">receivehsd</th>
<th data-quarto-table-cell-role="th">n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>11845.086</td>
<td>-30.0</td>
<td>0.416667</td>
<td>12</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>9205.679</td>
<td>-29.0</td>
<td>0.387097</td>
<td>31</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>8407.745</td>
<td>-28.0</td>
<td>0.318182</td>
<td>44</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>11114.087</td>
<td>-27.0</td>
<td>0.377778</td>
<td>45</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>10814.624</td>
<td>-26.0</td>
<td>0.306667</td>
<td>75</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Once again, this data is grouped by the running variable. It contains not only the running variable (minscore, already centered at zero) and the outcome (avgearnings), but it also has the probability of receiving a diploma in that score cell and the size of the call (n). So, for example, out of the 12 students in the cell -30 below the score threshold, only 5 were able to get the diploma (12 * 0,416).</p>
<p>This means that there is some slippage in the treatment assignment. Some students that are below the passing threshold managed to get the diploma anyway. Here, the regression discontinuity is <strong>fuzzy</strong>, rather than sharp. Notice how the probability of getting the diploma doesn’t jump from zero to one at the threshold. But it does jump from something like 50% to 90%.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>sheepskin.plot.scatter(x<span class="op">=</span><span class="st">"minscore"</span>, y<span class="op">=</span><span class="st">"receivehsd"</span>, figsize<span class="op">=</span>(<span class="dv">10</span>,<span class="dv">5</span>))</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Test Scores Relative to Cut off"</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Fraction Receiving Diplomas"</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Last-chance Exams"</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="W09. Regression Discontinuity_files/figure-html/cell-20-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>We can think of fuzzy RD as a sort of non compliance. Passing the threshold should make everyone receive the diploma, but some students, the never takers, don’t get it. Likewise, being below the threshold should prevent you from getting a diploma, but some students, the always takers, manage to get it anyway.</p>
<p>Just like when we have the potential outcome, we have the potential treatment status in this situation. <span class="math inline">\(T_1\)</span> is the treatment everyone would have received had they been above the threshold. <span class="math inline">\(T_0\)</span> is the treatment everyone would have received had they been below the threshold. As you’ve might have noticed, we can think of the <strong>threshold as an Instrumental Variable</strong>. Just as in IV, if we naively estimate the treatment effect, it will be biased towards zero.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://matheusfacure.github.io/python-causality-handbook/_images/rdd.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">img</figcaption><p></p>
</figure>
</div>
<p>The probability of treatment being less than one, even above the threshold, makes the outcome we observe less than the true potential outcome <span class="math inline">\(Y_1\)</span>. By the same token, the outcome we observe below the threshold is higher than the true potential outcome <span class="math inline">\(Y_0\)</span>. This makes it look like the treatment effect at the threshold is smaller than it actually is and we will have to use IV techniques to correct for that.</p>
<p>But first, let’s talk about a sanity check we need to run to make sure we can trust our RDD estimates.</p>
<section id="the-mccrary-test" class="level3">
<h3 class="anchored" data-anchor-id="the-mccrary-test">The McCrary Test</h3>
<p>One thing that could break our RDD argument is if people can manipulate where they stand at the threshold. In the sheepskin example this could happen if students just below the threshold found a way around the system to increase their test score by just a bit. Another example is when you need to be below a certain income level to get a government benefit. Some families might lower their income on purpose, just to be just eligible for the program.</p>
<p>In these sorts of situations, we tend to see a phenomenon called bunching on the density of the running variable. This means that we will have a lot of entities just above or just below the threshold. To check for that, we can plot the density function of the running variable and see if there are any spikes around the threshold. For our case, the density is given by the <code>n</code> column in our data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>,<span class="dv">8</span>))</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> plt.subplot(<span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">1</span>)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>sheepskin.plot.bar(x<span class="op">=</span><span class="st">"minscore"</span>, y<span class="op">=</span><span class="st">"n"</span>, ax<span class="op">=</span>ax)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"McCrary Test"</span>)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Smoothness at the Threshold"</span>)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> plt.subplot(<span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">2</span>, sharex<span class="op">=</span>ax)</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>sheepskin.replace({<span class="dv">1877</span>:<span class="dv">1977</span>, <span class="dv">1874</span>:<span class="dv">2277</span>}).plot.bar(x<span class="op">=</span><span class="st">"minscore"</span>, y<span class="op">=</span><span class="st">"n"</span>, ax<span class="op">=</span>ax)</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Test Scores Relative to Cut off"</span>)</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Spike at the Threshold"</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="W09. Regression Discontinuity_files/figure-html/cell-21-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>The first plot shows how our data density looks like. As we can see, there are no spikes around the threshold, meaning there is no bunching. Students are not manipulating where they fall on the threshold. Just for illustrative purposes, the second plot shows what bunching would look like if students could manipulate where they fall on the threshold. We would see a spike in the density for the cells just above the threshold, since many students would be on that cell, barely passing the exam.</p>
<p>Getting this out of the way, we can go back to estimate the sheepskin effect. As I’ve said before, the numerator of the Wald estimator can be estimated just like we did in the Sharp RD. Here, we will use as weight the kernel with a bandwidth of 15. Since we also have the cell size, we will multiply the kernel by the sample size to get a final weight for the cell.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>sheepsking_rdd <span class="op">=</span> sheepskin.assign(threshold<span class="op">=</span>(sheepskin[<span class="st">"minscore"</span>]<span class="op">&gt;</span><span class="dv">0</span>).astype(<span class="bu">int</span>))</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> smf.wls(<span class="st">"avgearnings~minscore*threshold"</span>,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>                sheepsking_rdd,</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>                weights<span class="op">=</span>kernel(sheepsking_rdd[<span class="st">"minscore"</span>], c<span class="op">=</span><span class="dv">0</span>, h<span class="op">=</span><span class="dv">15</span>)<span class="op">*</span>sheepsking_rdd[<span class="st">"n"</span>]).fit()</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>model.summary().tables[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="26">
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td></td>
<td data-quarto-table-cell-role="th">coef</td>
<td data-quarto-table-cell-role="th">std err</td>
<td data-quarto-table-cell-role="th">t</td>
<td data-quarto-table-cell-role="th">P&gt;|t|</td>
<td data-quarto-table-cell-role="th">[0.025</td>
<td data-quarto-table-cell-role="th">0.975]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Intercept</td>
<td>1.399e+04</td>
<td>83.678</td>
<td>167.181</td>
<td>0.000</td>
<td>1.38e+04</td>
<td>1.42e+04</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">minscore</td>
<td>181.6636</td>
<td>16.389</td>
<td>11.084</td>
<td>0.000</td>
<td>148.588</td>
<td>214.739</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">threshold</td>
<td>-97.7571</td>
<td>145.723</td>
<td>-0.671</td>
<td>0.506</td>
<td>-391.839</td>
<td>196.325</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">minscore:threshold</td>
<td>18.1955</td>
<td>30.311</td>
<td>0.600</td>
<td>0.552</td>
<td>-42.975</td>
<td>79.366</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>This is telling us that the effect of a diploma is -97.7571, but this is not statistically significant (P-value of 0.5). If we plot these results, we get a very continuous line at the threshold. More educated people indeed make more money, but there isn’t a jump at the point where they receive the 12th grade diploma. This is an argument in favor of the view that says that education increases earnings by making people more productive, rather than being just a signal to the marker. In other words, there is no sheepskin effect.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> sheepskin.plot.scatter(x<span class="op">=</span><span class="st">"minscore"</span>, y<span class="op">=</span><span class="st">"avgearnings"</span>, color<span class="op">=</span><span class="st">"C0"</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>sheepskin.assign(predictions<span class="op">=</span>model.fittedvalues).plot(x<span class="op">=</span><span class="st">"minscore"</span>, y<span class="op">=</span><span class="st">"predictions"</span>, ax<span class="op">=</span>ax, color<span class="op">=</span><span class="st">"C1"</span>, figsize<span class="op">=</span>(<span class="dv">8</span>,<span class="dv">5</span>))</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Test Scores Relative to Cutoff"</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Average Earnings"</span>)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Last-chance Exams"</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="W09. Regression Discontinuity_files/figure-html/cell-23-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>However, as we know from the way non compliance bias works, this result is biased towards zero. To correct for that, we need to scale it by the first stage and get the Wald estimator. Unfortunately, there isn’t a good Python implementation for this, so we will have to do it manually and use bootstrap to get the standard errors.</p>
<p>The code below runs the numerator of the Wald estimator just like we did before and also constructs the denominator by replacing the target variable with the treatment variable <code>receivehsd</code>. The final step just divides the numerator by the denominator.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> wald_rdd(data):</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>    weights<span class="op">=</span>kernel(data[<span class="st">"minscore"</span>], c<span class="op">=</span><span class="dv">0</span>, h<span class="op">=</span><span class="dv">15</span>)<span class="op">*</span>data[<span class="st">"n"</span>]</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>    denominator <span class="op">=</span> smf.wls(<span class="st">"receivehsd~minscore*threshold"</span>, data, weights<span class="op">=</span>weights).fit()</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>    numerator <span class="op">=</span> smf.wls(<span class="st">"avgearnings~minscore*threshold"</span>, data, weights<span class="op">=</span>weights).fit()</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> numerator.params[<span class="st">"threshold"</span>]<span class="op">/</span>denominator.params[<span class="st">"threshold"</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> joblib <span class="im">import</span> Parallel, delayed </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">45</span>)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>bootstrap_sample <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>ates <span class="op">=</span> Parallel(n_jobs<span class="op">=</span><span class="dv">4</span>)(delayed(wald_rdd)(sheepsking_rdd.sample(frac<span class="op">=</span><span class="dv">1</span>, replace<span class="op">=</span><span class="va">True</span>))</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>                          <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(bootstrap_sample))</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>ates <span class="op">=</span> np.array(ates)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>With the bootstrap samples, we can plot the distribution of ATEs and see where the 95% confidence interval is.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>sns.distplot(ates, kde<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>plt.vlines(np.percentile(ates, <span class="fl">2.5</span>), <span class="dv">0</span>, <span class="dv">100</span>, linestyles<span class="op">=</span><span class="st">"dotted"</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>plt.vlines(np.percentile(ates, <span class="fl">97.5</span>), <span class="dv">0</span>, <span class="dv">100</span>, linestyles<span class="op">=</span><span class="st">"dotted"</span>, label<span class="op">=</span><span class="st">"95% CI"</span>)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"ATE Bootstrap Distribution"</span>)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>plt.xlim([<span class="op">-</span><span class="dv">10000</span>, <span class="dv">10000</span>])</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>plt.legend()<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="W09. Regression Discontinuity_files/figure-html/cell-26-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>As you can see, even when we scale the effect by the first stage, it is still not statistically different from zero. This means that education doesn’t increase earnings by a simple sheepskin effect, but rather by increasing one’s productivity.</p>
</section>
</section>
<section id="key-ideas" class="level2">
<h2 class="anchored" data-anchor-id="key-ideas">Key Ideas</h2>
<p>We learned how to take advantage of artificial discontinuities to estimate causal effects. The idea is that we will have some artificial threshold that makes the probability of treatment jump. One example that we saw was how age makes the probability of drinking jump at 21 years. We could use that to estimate the impact of drinking on mortality rate. We use the fact that very close to the threshold, we have something close to a randomized trial. Entities very close to the threshold could have gone either way and what determines where they’ve landed is essentially random. With this, we can compare those just above and just below to get the treatment effect. We saw how we could do that with weighted linear regression using a kernel and how this even gave us, for free, standard errors for our ATE.</p>
<p>Then, we look at what would happen in the fuzzy RD design, where we have non compliance. We saw how we could approach the situation much like we did with IV.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>This workshop is a modification of Chapter 16 of the handbook <a href="https://github.com/matheusfacure/python-causality-handbook">Causal Inference for the Brave and True</a>.</p>
<p>I like to think of this entire book as a tribute to Joshua Angrist, Alberto Abadie and Christopher Walters for their amazing Econometrics class. Most of the ideas here are taken from their classes at the American Economic Association. Watching them is what is keeping me sane during this tough year of 2020. * <a href="https://www.aeaweb.org/conference/cont-ed/2017-webcasts">Cross-Section Econometrics</a> * <a href="https://www.aeaweb.org/conference/cont-ed/2020-webcasts">Mastering Mostly Harmless Econometrics</a></p>
<p>I’ll also like to reference the amazing books from Angrist. They have shown me that Econometrics, or ’Metrics as they call it, is not only extremely useful but also profoundly fun.</p>
<ul>
<li><a href="https://www.mostlyharmlesseconometrics.com/">Mostly Harmless Econometrics</a></li>
<li><a href="https://www.masteringmetrics.com/">Mastering ’Metrics</a></li>
</ul>
<p>Other important reference is Miguel Hernan and Jamie Robins’ book. It has been my trustworthy companion in the most thorny causal questions I had to answer.</p>
<ul>
<li><a href="https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/">Causal Inference Book</a></li>
</ul>
</section>
<section id="contribute" class="level2">
<h2 class="anchored" data-anchor-id="contribute">Contribute</h2>
<p>Causal Inference for the Brave and True is an open-source material on causal inference, the statistics of science. It uses only free software, based in Python. Its goal is to be accessible monetarily and intellectually. If you found this book valuable and you want to support it, please go to <a href="https://www.patreon.com/causal_inference_for_the_brave_and_true">Patreon</a>. If you are not ready to contribute financially, you can also help by fixing typos, suggesting edits or giving feedback on passages you didn’t understand. Just go to the book’s repository and <a href="https://github.com/matheusfacure/python-causality-handbook/issues">open an issue</a>. Finally, if you liked this content, please share it with others who might find it useful and give it a <a href="https://github.com/matheusfacure/python-causality-handbook/stargazers">star on GitHub</a>.</p>
</section>
</section>
<section id="assessed-question-1" class="level1">
<h1>Assessed Question</h1>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../notebooks/W08. Diff-in-Diff.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Difference in Differences</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->



</body></html>